### ISSUE TITLE
How to use create a disposable action on RefCount = 0 

### ISSUE THREAD

**Issue by avibe948** [RolandPheasant/DynamicData#101]
Hi Rolland, 
I use your Cache to implement a  real order blotter  here at one of London's financial institutions.
Your works is very impressive. 
For RefCount 
I understand that the last call will dispose the cache. However I need to dispose /unsubscribe another source and wondered how I can achieve it. 
If I use the  pattern  below (replacing subject with your order source  ) it will return IDisposable whereas I rely on 
IObservableCache<CompositeOrder, IComparable> GetOrderSourceCache() .... 

  r public IObservableCache<CompositeOrder, IComparable> GetOrderSourceCache()
        {
            _orderSource.Clear();
            Log.Error($"subscription failed for portfolio using order filter {_orderFilter.Portfolio}");
            return Observable.Create(observer =>
            {
                var subscription = _orderSource.Connect().Subscribe(observer);
                var unsubscribe = Disposable.Create(() =>
                {
                    Log.Info($"OrderSource being disposed as the last subscriber disconnected");
                      _operationController.UnSubscribe(OnOrderUpdate, Topic.Order); // that's what I need to call when the last subscriber disconnected 
     
                });
                return new CompositeDisposable(subscription, unsubscribe);
            });
        }.Publish().RefCount() 

This is based on http://www.jasonhales.co.uk/2015/01/using-rxs-refcount-extension-to-create.html

Thanks,
Avi

**Comment by RolandPheasant** [comment]
First of all which version are you using?

Secondly I have recently introduced ObservableChangeSet.Create methods which make the cache behave like a first class observable. See https://github.com/RolandPheasant/DynamicData.Snippets/blob/master/DynamicData.Snippets/Creation/ChangeSetCreation.cs for example usages + some unit tests.

Also if you want, send your email address to me (my address is on the dd github homepage) and I will send an invite to the slack forum as it is easier to discuss there.

**Comment by avibe948** [comment]
Hi Roland , 
This was not an issue at all , it works great for us , super fast , Great work ! 
    On Monday, 19 March 2018, 22:06:20 GMT, Roland Pheasant <notifications@github.com> wrote:  
 
 
Closed #101.
