### ISSUE TITLE
How to split SourceCache into two sequence to combine them later

### ISSUE THREAD

**Issue by Allesad** [RolandPheasant/DynamicData#103]
Hi, Rolland. Thank you for your awesome library! I'm a bit familiar with reactive programming and now I'm trying to embrace your library and its set of operators.

I'm trying to merge two observable change sets together using And<> method but I'm failing to do so. I have an object with collection of items which I want to filter, sort and perform some aggregations on. Data object passed into constructor have current version of this list.

But after object creation I have to maintain it's state not via constructor but from some exposed method.
And the problem is that I still need to have deleted items in the list just mark them as "deleted".

So I'm trying to split result items list into two: for current items and for "deleted" items. I created single `SourceCache<>` and tried to connect to it using two separate rx-streams to combine them later.
```
public OrderProxy(Order order)
{
	...
	// Create single cache
	_allItems = new SourceCache<OrderItemProxy, Guid>(item => item.Id);
	// Add initial items
	_allItems.AddOrUpdate(order.Items);
	
	// Create deleted items stream
	var deletedItems = _allItems.Connect()
		.WhereReasonsAre(ChangeReason.Remove)
                // Transform to "deleted" proxy
		.Transform(item => new OrderItemProxy(item, isDeleted: true)); 
		
	// create result items stream with combined current and "deleted" items
	var combinedItems = _allItems.Connect()
                // Transform to non-deleted proxy
		.Transform(item => new OrderItemProxy(item)) 
		.And(deletedItems) // Combine with deleted items
		.AsObservable();
		
	// Calculate aggregations
	var counters = combinedItems
		.Filter(item => !item.IsDeleted) // Non-deleted items only
		.ToCollection()
		.ObserveOnDispatcher()
		.Subscribe(items =>
		{
			TotalCount = items.Count;
			NotReadyCount = items.Count(item => item.Status != Status.Ready);
		});
		
	var res = combinedItems.Sort(...Some sorting...)
		.ObserveOnDispatcher()
		.Bind(out _items) // Bind to items output
		.Subscribe();
		
	_cleanUp = new CompositeDisposable(counters, res);
}
```
Initial state is correct, but when I'm trying to update items using `_allItems.EditDiff(newItems, new ItemsChangesComparer())` my `deletedItems.Transform(`) never invokes.
And aggregations calculation failed due to empty items set passed to Subscribe() so all counters set to 0.

When I tried to apply `.WhereReasonsAreNot(ChangeReason.Remove)` operator to non-deleted items stream I got not update whatsoever. I mean .Transform() is applied but no changes applied to _items output.
What's happening here? Why `.WhereReasonsAre(ChangeReason.Remove)` not passed stream values further? I looked into the stream using .Do() and Remove-type changes are there.
Do I using operators wrong? Do I need some .Publis()-.Connect() parts applied? I tried to do so with combinedItems stream but to no avail.

**Comment by RolandPheasant** [comment]
You are very close to achieving the desired result. There are parts which require changing.

First of all, when you filter on ```WhereReasonsAre(ChangeReason.Remove)``` you still receive a change set of removes, and when the change set is processed, it tries to remove an item from it's internal state. The object will not exist so the remove instruction is ignored.

The way to resolve this is to create a local cache which you manually populate with the deleted items.

```
var deletedItemsCache = new SourceCache<OrderItemProxy, Guid>(item => item.Id);

var deletedItemsPopulator = _allItems.Connect()
	.WhereReasonsAre(ChangeReason.Remove)
        //extract removed items using standard rx
        .Select(changes => changes.Select(change=>change.Current))
        .Subscribe(deletedItems.AddOrtUpdate(items)));
``` 

Now you can transform the deleted order

```
// Create deleted items stream from the local cache 
var deletedItems = deletedItemsCache .Connect()
	.Transform(item => new OrderItemProxy(item, isDeleted: true)); 
```

Instead of the ```And``` operator you will need to use the ```Or``` operator as ```And``` will include all results where the key matches in both data sources whereas ```Or``` will include items in either data source.

The only other consideration is that the deleted items is unbounded and may continually grow.  If need be you can, make use the size and time limit operators

```
var expirer = deletedItemsCache 
      .ExpireAfter(t=> TimeSpan.FromMinutes(1), Scheduler.Default)
      .Subscribe(x => Console.WriteLine($"{x.Count()} items removed"));
```
or 

```
var expirer = deletedItemsCache 
      .LimitSizeTo(100)
      .Subscribe(x => Console.WriteLine($"{x.Count()} items removed"));
```

**Comment by Allesad** [comment]
Thank you for such quick response! Initially I was thinking about separate cache for deleted Items but I thought I could be able to separate stream in two in one go.
