### ISSUE TITLE
Deriving an observable list removes wrong item with TransformMany

### ISSUE THREAD

**Issue by WernerGe** [RolandPheasant/DynamicData#108]
Hi,

I have written a small DynamicData test (please see the attached LinqPad sample) which does not work correctly removing an item  on an ObservableList derived from a SourceList with TransformMany (see attached LinqpadOutput).
The remove operation removes a wrong item marked with
	// FAILS !!!!!!!!!!!! tour3_1 is removed, tour2_1 remains ?!?

[GtgTest_NotWorking.linq.txt](https://github.com/RolandPheasant/DynamicData/files/1825590/GtgTest_NotWorking.linq.txt)

[GtgTest_NotWorking.xlsx](https://github.com/RolandPheasant/DynamicData/files/1825591/GtgTest_NotWorking.xlsx)

Best regards,

Werner

**Comment by RolandPheasant** [comment]
I will take a look. If you would like to join the community on slack (easier to discuss issues on a forums)  then send your email address to me roland@dynamic-data.org and I will send an invite

**Comment by RolandPheasant** [comment]
I managed to replicate the issue. It has been fixed and deployed to Nuget  v 6.1.3.2378

**Comment by WernerGe** [comment]
Hi Roland,

just tested it - works perfect 👍 thanlks for the prompt solution :-)

Best regards,

Werner
