### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by dmitrykm** [RolandPheasant/DynamicData#109]
Hello Roland,

Is the following use case supported? 
```CSharp
 public class DdTest : IDisposable
    {
        private readonly IDisposable _subscription;
        private readonly SourceList<int> _src = new SourceList<int>();
        private bool _isDisposed;

        public DdTest()
        {
            _subscription = _src.Connect()
                .OnItemRemoved(videoSourceId =>
                {
                    Thread.Sleep(20);
                })
                .Subscribe();

            Task.Run(() =>
            {
                while (!_isDisposed)
                {
                    _src.Add(4);
                    _src.Remove(4);
                    Thread.Sleep(10);
                }

                // ReSharper disable once FunctionNeverReturns
            });
        }

        public void Dispose()
        {
            if (_isDisposed)
                return;

            _isDisposed = true;
            _subscription.Dispose();
            _src.Dispose();
        }
    }

    [TestFixture]
    public class TestDd
    {
        [Test]
        public async Task TestAsync()
        {
            var ddTest = new DdTest();
            await Task.Delay(2000);
            ddTest.Dispose();
        }
    }
```
For me, `ddTest.Dispose();` throws "Collection was modified; enumeration operation may not execute"

**Comment by RolandPheasant** [comment]
``` Thread.Sleep``` has no place in reactive programming, nor does polling!  Such things will always lead to problems.

In reactive you would normally control threading and timing one of the many build in rx operators coupled with a scheduler.  Also there are several operators which assist with integrating the Tasks API.

In terms of the error when disposing, I can mitigate against the chances of this happening and will do so some time.

**Comment by RolandPheasant** [comment]
The dispose issue has been fixed and will be in the next release

**Comment by dmitrykm** [comment]
Thank you for the reply and fix. In the real app where this issue happened, there is no Thread.Sleep. In this test example it helps to reproduce the issue.

**Comment by RolandPheasant** [comment]
Ha. Anyway it is fixed now
