### ISSUE TITLE
Introduce covariance and contravariance on the interfaces

### ISSUE THREAD

**Issue by loicmorvan** [RolandPheasant/DynamicData#112]
Can you introduce covariance and contravariance on the interfaces of DynamicData?

For example`IObservableCache<TObject, TKey>` could become `IObservableCache<out TObject, in TKey>`.
It would help us to apply the Liskov Substitution Principle when exposing interfaces of DynamicData.

Thanks!

**Comment by robsonj** [comment]
Any thoughts on this Roland. I'd be happy to take a look at it as a way to re-introducing myself to contributing to this project, unless you have other thoughts/input

**Comment by RolandPheasant** [comment]
Feel free to try. 

The part of the cache / list which exposes the inner items directly make this task easier said than done

**Comment by robsonj** [comment]
Yea, got as far as the Change<,> which is a struct

**Comment by loicmorvan** [comment]
Too bad... I suppose the use of a `struct` here is for performance reasons?

**Comment by robsonj** [comment]
Performance and memory I would imagine, the two are usually interlinked also, especially with regard to GC.
