### ISSUE TITLE
Removed item(LimitSizeTo) cannot be garbage collected when using SourceList Sort 

### ISSUE THREAD

**Issue by decryp7** [RolandPheasant/DynamicData#119]
When using LimitSizeTo with Sort, removed item cannot be garbage collected.
On the memory profiler, it seems that Sort Closure is holding on to the item.

![image](https://user-images.githubusercontent.com/12887997/40158082-1f924270-59d5-11e8-8704-b06324c22c51.jpeg)

**Comment by RolandPheasant** [comment]
This is fixed now. I will release soon if it is urgent for you.

**Comment by decryp7** [comment]
Hi,

Thank you. Can you release soon because I need it?

**Comment by decryp7** [comment]
Hi,

I have tested and confirmed that this issue is resolved.
Thank you!
