### ISSUE TITLE
DynamicData should be updated to support System.Reactive >= 4.0.0

### ISSUE THREAD

**Issue by glennawatson** [RolandPheasant/DynamicData#124]
Might need System.Reactive.Compatibility package, otherwise should just be System.Reactive package now due to the auto-resolve feature set.

**Comment by RolandPheasant** [comment]
Maybe it is just a case of removing the max version constraint in the csproj file

**Comment by glennawatson** [comment]
Yeah I think so.

**Comment by glennawatson** [comment]
This is resolve with 6.4.
