### ISSUE TITLE
[Feature] Move SuspendNotifications to its own interface

### ISSUE THREAD

**Issue by gsivorot** [RolandPheasant/DynamicData#125]
It would be useful to be able to use SuspendNotifications without having to know the GenericType it's being used on. IObservableCollection<T> could inherit the new interface.  In WPF custom controls use non-generic types like IList and IEnumerable so in those situations I currently have to use reflection to call SuspendNotifications on supported types.

**Comment by RolandPheasant** [comment]
This is easily achieved so I'll do it.

**Comment by gsivorot** [comment]
Awesome, thanks!

**Comment by RolandPheasant** [comment]
We now have 

INotifyCollectionChangedSuspender
