### ISSUE TITLE
Add a Filter overload that takes a static predicate and a reapplyFilter

### ISSUE THREAD

**Issue by gdurand** [RolandPheasant/DynamicData#129]
Currently you cannot refresh a cache filtered with a static predicate.
An overload `Filter(Func<TObject, bool> filter, IObservable<Unit> reapplyFilter)` could be useful.

**Comment by robsonj** [comment]
Would this need to apply to Connect(predicate) also for API parity?

**Comment by gdurand** [comment]
Connect(predicate) may be considered a convenience overload, so it would be acceptable to have reduced functionality.
So not mandatory for me.

**Comment by robsonj** [comment]
No. As we found, with thanks to Roland, it has significant memory advantages over the .Filter(predicate) operator

**Comment by gdurand** [comment]
Just for my understanding: how so?
- `Connect(predicate)` returns `changes.Filter(predicate)`
- `Connect()` returns `changes `on which you can call `Filter(predicate)`, which to me looks very much the same as `changes.Filter(predicate)`

**Comment by RolandPheasant** [comment]
It's not the same because it applies a prefilter first thus reducing the filter operator overhead

**Comment by gdurand** [comment]
Indeed.
In this case you may want to indicate in the doc of `predicate` (or even better, in Connect()) that using a predicate in Connect is preferred to using Connect().Filter(predicate)
