### ISSUE TITLE
parameter change

### ISSUE THREAD

**Issue by dtaylor-530** [RolandPheasant/DynamicData#130]
Thankyou very much for the library. 
in version 6 4 0 2419 of DynamicData
<img width="548" alt="6 4 0 2419" src="https://user-images.githubusercontent.com/28949645/42264228-f665a96a-7f67-11e8-92ab-5b990939e4bb.png">
the TotalSize property corresponds with Page and vice versa

a change from 6 1 3 2378
<img width="472" alt="6 1 3 2378" src="https://user-images.githubusercontent.com/28949645/42264246-02980d7c-7f68-11e8-83a4-8422959f87fe.png">

Also perhaps worth mentioning in the readme that IChangeSet needs to be cast to IPageChangeSet for use in pagination (again a change from the version in Dynamic.Trader)

**Comment by RolandPheasant** [comment]
In the first image, you are using an observable list because no key is specified whereas the example in the second example from Dynamic Trader it is using an observable cache.

The error is that the list overload of page. I will fix the API (both issues) when I get a chance.

**Comment by dtaylor-530** [comment]
i thought i was missing something. Thanks for the info.
