### ISSUE TITLE
Synchronization  to a bound Observable Collection  

### ISSUE THREAD

**Issue by avibe948** [RolandPheasant/DynamicData#131]
Hi Roland,

We use your library in a real production application ( commodities order blotter ). Works great. 
I have the following  problem to solve. 
I have a price stream that updates prices and each order item need to change its color based on the latest market price which is compared to the limit price on the order item. So I have two streams a price stream and the order cache source  stream. The order cache source is bound to an observable collection. 
I need to be able to lock the bound observable collection  for write operation while a specific price stream event happens  ( as the price stream event iterates through the bound observable collection and updates the prices).  
Or Do it the RX way and  use combined latest to combine the orders cache source observable with the  prices stream.
Locking the prompt stream while processing each item inside of  transform won't work as I need to lock the entire collection. 

I would appreciate your view on how the library can resolve these kind of issues. 

here is my order cache connectable. 

     var ordersCacheConnectable = Observable.Defer(()=> orderSourceCache.Connect());
            var orderSubscription= ordersCacheConnectable
                .Filter(compOrder =>
                {
                        var include = ProductTypeFilter(compOrder.CompositeOrderProductType) &&
                                  compOrder.LatestCompositeOrderWorkflow.CompositeOrderStatus !=
                                  CompositeOrderStatus.Reissued &&
                                       GetOrderPanelAllocation(compOrder).HasFlag(OrderBlotterStatusPanelAllocation);
                        return include;
                })
                .Transform(ProcessOrderChangeNotification)
                .ObserveOn(schedulerService.Dispatcher)
                .SubscribeOn(schedulerService.ThreadPool)
                .Bind(_orderBlotterItemViewModels)
                .DisposeMany()
                .Subscribe(ord =>
                {
                    SortOrderBlotter();
                    ProcessChangeSet(ord);
                }, OnOrderSourceCacheError);

**Comment by RolandPheasant** [comment]
The first question is why do you need to lock the cache stream? Is it because you are sorting on market data? The answer to this question may change any advice.

My preferred option would be to have the orders individually subscribe to an observable of prices (which can be filtered by a key) and process their own values locally.  That way the order becomes autonomous and no locking is required.  I have used this methodology many times and conceptually it works very well. 

Also to help me understand your scenario better, why are you sorting and processing changes within```Subscribe```.   Such things are always better within the observable.  If you are sorting by price, there are several techniques within dynamic data where you can have fine grained control of sorting using either the ```Sort``` or ```AutoRefresh``` operators.

**Comment by avibe948** [comment]
Hi Rolland, 
1)  I don't need to lock the stream but I need to lock the bound order collection. The reason for that is that we have a requirement to change the background color of each  row that presents the order. 
The row contains a limit price and a current market price so there is a rule that states that if the limit price ><= current market price I need to change the background of the row. So there is a price stream observable that receives price changed notification and then iterates over all the orders in the bound order collection and injects the current market price into them. 
The reason we need to synchronize these streams is that the bound Order collection can change at the same time that the price stream changed. At the moment I only lock the latest price shared object using Write when the price changes and then enter a read lock when I read it and write it to each row in the order collection ( upon price change).
Your idea to subscribe to the price change on each order will work but will require refactoring which I will do now. Thanks for your advice !
 
2) Sorting is done in subscribe and not using your Sort function (which I used before ) because the sorting is complex. I am aware that this is not ideal as it sorts on the arrival of each item but for the number of records we have the performance is very good so its not an issue. The sorting uses IComparer<OrderBlotterItemModel> and as far as  I recall when I wrote it 6m ago I couldn't get it to work with Sort operator , even though it takes IComparer. Looking at it again , I don't see why it wouldn't work and I don't remember the details so I will have to try to change it and retest. The sort function have side effects to inject something into the bound order collection, but this can probably be done via Do , or ObservableCollectionAdapter  , and really doesn't need to be apart of sort. 

private void SortOrderBlotter()
        {
            if (!OrderBlotterItemViewModels.Contains(_promptPriceOrderBlotterItem) &&
                _promptPriceOrderBlotterItem != null)
                OrderBlotterItemViewModels.Add(_promptPriceOrderBlotterItem);

            OrderBlotterItemViewModels.Sort(_orderBlotterItemComparer);
        }

Thanks again for your useful advice

**Comment by RolandPheasant** [comment]
There will be a way to make sort work directly but perhaps I can help you with that another time.  If the collection alone needs to be locked you can do something like this:

```cs
var locker = new object();

...   
    .Synchonize(locker) 
    .Bind(_orderBlotterItemViewModels)
    .DisposeMany()

var myOrderUpdaterObservable = ...
    .Synchonize(locker) 
    .Subscribe(_=> ..) \\process orders directly from the observable collection;
```

This may work, but locking from outside an observable stream is always a little tricky
