### ISSUE TITLE
Upgrade to System.Reactive 4.0

### ISSUE THREAD

**Issue by glennawatson** [RolandPheasant/DynamicData#137]
Upgrading to 4.0 will allow your API to be consumed in other packages without the need of the System.Reactive.Compatibility package. 

I will submit a PR soon.

**Comment by glennawatson** [comment]
Fixed by https://github.com/RolandPheasant/DynamicData/pull/138

**Comment by j2ghz** [comment]
Is there a way to get a notification when this gets released on nuget?

**Comment by glennawatson** [comment]
I personally use https://coderelease.io
