### ISSUE TITLE
Filtering after sorting

### ISSUE THREAD

**Issue by lummoj** [RolandPheasant/DynamicData#141]
Hi there, first I'd like to say I'm very impressed with this library. I've being using it to replace some difficult to maintain sorting and filtering logic with DynamicData and while it's working well I have ran into issues with filtering after sorting (starting with a SourceCache).

From what I can see it's due to the transformation of ISortedChangeSet (after sorting) back to IChangeSet (after filtering) before binding to a ReadOnlyObservableCollection.

Is it possible to preserve ISortedChangeSet after Filter or other operations such as Buffer and BufferInitial?

The use case for this is where a large list is sorted and then additional filtering is applied to produce a number of different 'views' but I'd like to preserve or reuse the sort order of the original data rather than having to sort again in order to use operators such as Virtualise and Bind.

I have worked around this for now by sorting again in the 'views' before Bind but that doesn't seem quite right.

**Comment by RolandPheasant** [comment]
Unfortunately the sort order cannot be maintained in the cahe part of the system because it is dictionary based and the additional burden of maintaing indices would kill performance as well as adding huge complexities.

The work around which you are using is a common pattern for dealing with this.
