### ISSUE TITLE
UWP Version

### ISSUE THREAD

**Issue by Pinox** [RolandPheasant/DynamicData#145]
Hi @RolandPheasant 

Want to start playing with dynamic data, looks like a great lib ;)

Any pointers to a UWP sample that does not rely on the old version 3 compat libraries in Reactive.

**Comment by glennawatson** [comment]
If you use System.Reactive.Compatibility 4.0/4.1 it just does a binding redirect to the latest version. 

I did a PR to upgrade to 4.0 a couple weeks back so when Roland does another release it should be pure 4.0.

**Comment by RolandPheasant** [comment]
I will do a release this week.

**Comment by Pinox** [comment]
@RolandPheasant @glennawatson  thanks guys.
