### ISSUE TITLE
Use SourceLink to enable debugging from the GitHub  code base

### ISSUE THREAD

**Issue by RolandPheasant** [RolandPheasant/DynamicData#147]
This would be cool. I need to do some research to find out how to do it. If anyone is able to help please do so.

**Comment by glennawatson** [comment]
We use this one on our Rx projects https://github.com/dotnet/sourcelink

**Comment by ltrzesniewski** [comment]
I'm using this thing on a couple libraries. It works wonders. I can give a shot at a PR.

**Comment by RolandPheasant** [comment]
@ltrzesniewski I would be delighted if you could do that

**Comment by ltrzesniewski** [comment]
Sure thing, here you go 😄
