### ISSUE TITLE
Replace source when Binding to collection

### ISSUE THREAD

**Issue by bezysoftware** [RolandPheasant/DynamicData#169]
Hi, I'm just getting started with your lib and have a following scenario - I have a source collection (ObservableCollection at the moment) that I want to transform, sort, group and bind to a UI collection. This works great.
Now I need to be able to replace the entire source collection for a different instance. Is there a way to do this without creating a observable chain (and disposing the original one)? I tried this (uses ReactiveUI):

```csharp
// Ints is the source
this.WhenAnyValue(x => x.Ints)
	.Do(_ => this.FilteredInts.Clear()) // Clear binding target
	.ToObservableChangeSet()
	.TransformMany(i => i)
	.GroupOn(i => (int)(i / 10))
	.Transform(group => new Grouping<int, int>(group))
	.Sort(SortExpressionComparer<Grouping<int, int>>.Ascending(t => t.Key))
	.ObserveOnDispatcher()
	.Bind(this.FilteredInts)
	.Subscribe();

...
public ObservableCollection<int> Ints { get { ... }; private set { ... } };
public ObservableCollectionExtended<Grouping<int, int>> FilteredInts { get { ... }; private set { ... } }
...
// somewhere in a method replace the source which triggers "WhenAnyValue"
this.Ints = new ObservableCollection<int>();
```

This works with the start of the app, but as soon as I replace the source (```Ints```) the target binding collection becomes empty. If I remove the ```.Do(...)``` operator where I clear it, the items from the previous instance of the source remain there, but I need them gone because they don't belong to the new source.

Any ideas? If course I could create the whole stream anew each time the source collection changes, but that adds complexity as I need to take care of disposing of the original subscription.

Thanks

**Comment by bezysoftware** [comment]
Actually I just noticed and exception is thrown after I try to add a new item to the new source:

```System.ArgumentOutOfRangeException: Index must be within the bounds of the List.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.ObjectModel.Collection`1.Insert(Int32 index, T item)
   at DynamicData.ListEx.Clone[T](IList`1 source, Change`1 item)
   at DynamicData.ListEx.Clone[T](IList`1 source, IChangeSet`1 changes)
   at DynamicData.Binding.ObservableCollectionAdaptor`1.Adapt(IChangeSet`1```

**Comment by RolandPheasant** [comment]
Bind works on the basis that the operator is in complete control of the bound collection. That is why I always recommend using the ReadOnlyObervableCollection overload. 

For your use case you should populate a source list and maintain the data there. I'm such a case the binding will always reflect exactly what you want

**Comment by RolandPheasant** [comment]
There are several examples of similar functionality  here RolandPheasant/DynamicData.Snippets

**Comment by bezysoftware** [comment]
Fantastic, thanks a lot. Also for the snippets repo, wasn't aware of it
