### ISSUE TITLE
TransformMany with Refresh

### ISSUE THREAD

**Issue by Liklainy** [RolandPheasant/DynamicData#173]
Hello, I have an issue with TransformMany:
```csharp
[Fact]
public void Refresh()
{
    var relations = new List<Person> { new Person("Child1", 1) };
    var parent = new PersonWithChildren("parent", 50, relations);
    _source.AddOrUpdate(parent);

    relations.Add(new Person("Child2", 2));
    _source.Refresh(parent); //_source.AddOrUpdate(parent);

    _results.Data.Count.Should().Be(2, "Should be 2 in the cache");
    _results.Data.Lookup("Child1").HasValue.Should().BeTrue();
    _results.Data.Lookup("Child2").HasValue.Should().BeTrue();
}
```
The test will fail.
Because TransformMany on `Refresh` doesn't add or remove items it only propagates `Refresh`.
TransformMany internally uses Transform with `transformOnRefresh = false` by default.

I can see that changing `Relations` from `IEnumerable` to `ObservableCollection` will fix it and there will be no need for explicit `Refresh`.
```csharp
public ObservableCollection<Person> Relations { get; }
parent.Relations.Add(new Person("Child2", 2));
```

Are there other ways to do it?
Probably add `transformOnRefresh` parameter to TransformMany?

**Comment by RolandPheasant** [comment]
I recommend using an observable collection as the API explicitly states that the contents of the collection can change. However for completeness it would be best to add the transformOnRefresh overload.

**Comment by samirem** [comment]
I stumbled upon a similar issue in my code where an `AutoRefresh` triggered an update in the `TransformMany` which then threw an `ArgumentOutOfRangeException`, see #172.

My PR simply makes sure that the exception is not thrown, but the desired functionality from my point of view is that the `TransformMany` should be reevaluated whenever a `ListChangeReason.Refresh` is triggered from an item in the stream. I'm new to this library, so not sure how it should be implemented. @Liklainy does your PR adress this?

**Comment by Liklainy** [comment]
I ended up trying to fix list's behavior in the same pull request
