### ISSUE TITLE
Change name?

### ISSUE THREAD

**Issue by wexman** [RolandPheasant/DynamicData#176]
This might actually be rude to request (and I don't expect you to do so), but have you considered changing the name of this project? DynamicData is suboptimal, because it not only conflicts with asp.net dynamic data, but it's hard to google all by itself.
ReactiveCollections or something might have been better...

**Comment by glennawatson** [comment]
The problem with ReactiveCollection is reactive ui had one and was only deprecated recently.

**Comment by RolandPheasant** [comment]
The name Dynamic Data is reasonably accurate description of what it is.  

Further to Glenn's point,  and something that few people know is that Dynamic Data existed for a long time before I open sourced it. The original name of the project was ActiveList and was implemented using old school events. After converting it to use Rx and also before I open sourced it, it's name was ReactiveList. I subsequently changed the name to DynamicData when I stumbled upon  ReactiveList existing in ReactiveUI.

I agree it is unfortunate about the clash with the ASP dynamic data but I have figured all along that no one uses that any more so it does not matter.

But above all else it is impractical to change the name of a project and the subsequent namespace changes as it will break thousands of projects for zero benefit.

**Comment by wexman** [comment]
I apologize if my suggestion sounded rude, it wasn't meant to!

I'm new to this reactive stuff and having a hard time learning the basics (but I feel it's potential!). And every time I try to google for a solution I'm getting lots of results for asp.net dynamic data (although that is dead indeed)...

Where would be the right place to ask beginner's questions?

**Comment by glennawatson** [comment]
Feel free to jump on the slack channel. https://reactiveui.net/slack and join channel #dynamicdata

Most of the .net reactive teams are on there.

**Comment by wexman** [comment]
I apologize if my suggestion sounded rude, it wasn't meant to!

I'm new to this reactive stuff and having a hard time learning the basics (but I feel it's potential!). And every time I try to google for a solution I'm getting lots of results for asp.net dynamic data (although that is dead indeed)...

Where would be the right place to ask beginner's questions?

**Comment by wexman** [comment]
Thanks, just joined the slack channel...
