### ISSUE TITLE
Transform Tree Test

### ISSUE THREAD

**Issue by redoced** [RolandPheasant/DynamicData#177]
https://github.com/RolandPheasant/DynamicData/blob/447b9c1642f0214fdc4e0a4351a25bb352c2ac1e/DynamicData.Tests/Cache/TransformTreeFixture.cs#L133-L134

was reading up on these tree functions and wondered if this is not supposed to be

            _sourceCache.AddOrUpdate(minion);
            _sourceCache.AddOrUpdate(boss);

ie adding the minion first and the boss second... otherwise I don't see any difference between `AddMissingParent()` and `AddMissingChild()`

**Comment by RolandPheasant** [comment]
It has been years since I looked at TransformToTree so off the top off my head I cannot say,
