### ISSUE TITLE
AutoRefresh bug with ObservableList

### ISSUE THREAD

**Issue by samirem** [RolandPheasant/DynamicData#181]
When using an `ObservableList` in the following sample:
```
ObsList.Connect()
    .AutoRefresh(x => x.SomeProperty)
    .Filter(x => someFilter)
    .AsObservableList();
```
it failed to update when `SomeProperty` changed. However, when changing to `ObservableCache` like
```
ObsCache.Connect()
    .AutoRefresh(x => x.SomeProperty)
    .Filter(x => someFilter)
    .AsObservableCache();
```
it seems to work fine.

Tried with version 6.6.1.2516 of the library.

**Comment by rschoenbach** [comment]
I am having the same issue with a slightly different set of operators.

    ObsList.Connect()
        .Transform(x= new ViewModel(x))
        .AutoRefresh(x => x.SomeBool)
        .Filter(x => x.someBool)

The filter is not being triggered.

**Comment by rschoenbach** [comment]
@RolandPheasant Thank you for the reply. I put together tests cases and I could not reproduce the issue in test. When I add in 3rd party UI controls and bind to the ReadOnlyObservableCollection something get messed up. For now, I have a work around. Apologies for the false alarm.

**Comment by samirem** [comment]
I'm away for a week on a business trip. Will provide a repro when I get back home.

**Comment by WernerGe** [comment]
I have attached a LinqPad sample using AutoRefresh and Filter on both SourceList and SourceCache. Changing the filter property SourceCache should remove the item from the filtered list. SourceCache works fine, using SourceList the item remains.
[DynamicData_AutoRefreshWithFilter.zip](https://github.com/RolandPheasant/DynamicData/files/2571581/DynamicData_AutoRefreshWithFilter.zip)

**Comment by WernerGe** [comment]
... slightly better version of LinqPad sample reinitialising test data for SourceCache
[DynamicData_AutoRefreshWithFilter.zip](https://github.com/RolandPheasant/DynamicData/files/2571665/DynamicData_AutoRefreshWithFilter.zip)

**Comment by RolandPheasant** [comment]
Thanks. I will look at this after my day job

**Comment by WernerGe** [comment]
... another observation with the DynamicData_AutoRefreshWithFilter LinqPad sample
using
```i1.Name = "X2";```
the derived list gets updated !

Using
```obsList.Items.First().Name = "X2";```
the derived list gets NOT updated

**Comment by WernerGe** [comment]
... isolating above for SourceCache suddenly fails, too ?!? (MsTest)
```
        /// <summary>
        /// Test if a filtered derived source cache is updated when the AutoRefresh property changes.
        /// The change is done directly on the property object.
        /// </summary>
        /// <remarks>
        /// Did not work with DynamicData V 6.6.1.2507 (DynamicData issue #181)
        /// </remarks>
        [TestMethod]
        public void DynData_AutoRefreshFilter_SourceCache_TestIssue181()
        {
            var a0 = new TestItem("A0");
            var i1 = new TestItem("I1");
            var i2 = new TestItem("I2");
            var i3 = new TestItem("I3");

            // SourceCache worked on AutoRefresh/Filter (DynamicData issue #181)
            var sourceCache = new SourceCache<TestItem, Guid>(x => x.Id);

            sourceCache.AddOrUpdateRange(new[] { a0, i1, i2, i3 });

            var filteredItems = sourceCache.Connect()
                .AutoRefresh(x => x.Name)
                .Filter(x => x.Name.Contains("I"))
                .AsObservableCache();

            // a0 was immediately filtered out
            (new[] { i1, i2, i3 }).AssertElementsEqual(filteredItems.Items, ordered: false);

            // Change Property items are filtered with => item no longer in filter must be removed automatically
            sourceCache.Items.First().Name = "X2";

            (new[] { i2, i3 }).AssertElementsEqual(filteredItems.Items, ordered: false);
        }
```

**Comment by RolandPheasant** [comment]
I just ran the linq pad example and I still do not see anything wrong.

The line   

```cs
obsList.Items.First().Name = "X2"
```
is updating the first item, ie item with name = "A0" which does not match the filter. Settting it to "X2" still does not match the filter so no change in the derived cache is expected.

If instead you invoke this line 

```cs 
 i1.Name = "X2";
```
There will be 2 items in the list. That is because an item which previously matched the filter no longer does so

**Comment by WernerGe** [comment]
Hi Roland,

I have attached you 2 screenshots showing the difference I observe on my
LinqPad.
I'm using EITHER First() OR direct change (NOT BOTH)

Best regards,

Werner


Am Mo., 12. Nov. 2018 um 21:59 Uhr schrieb Roland Pheasant <
notifications@github.com>:

**Comment by RolandPheasant** [comment]
Create a project, install Xunit and FluentAssertions. Then paste this in 

```cs
public class AutoRefreshFilter
{
    [Fact]
    public void Test()
    {
        var a0 = new Item("A0");
        var i1 = new Item("I1");
        var i2 = new Item("I2");
        var i3 = new Item("I3");

        var obsList = new SourceList<Item>();
        obsList.AddRange(new[] {a0, i1, i2, i3});

        var obsListDerived = obsList.Connect()
            .AutoRefresh(x => x.Name)
            .Filter(x => x.Name.Contains("I"))
            .AsObservableList();

        obsListDerived.Count.Should().Be(3);
        obsListDerived.Items.Should().BeEquivalentTo(new[] {i1, i2, i3});

        i1.Name = "X2";
        obsListDerived.Count.Should().Be(2);
        obsListDerived.Items.Should().BeEquivalentTo(new[] {i2, i3});

        a0.Name = "I0";
        obsListDerived.Count.Should().Be(3);
        obsListDerived.Items.Should().BeEquivalentTo(new[] {a0, i2, i3});
    }
}
```

The tests pass as expected

**Comment by WernerGe** [comment]
... ok, now I have your point - I was writing obsList instead of obsListDerived with the First() line and thought, this would reproduce the issue reported ;-) correcting this everything works fine therefore cannot reproduce the issue reported.
