### ISSUE TITLE
ExpireAfter in ToObservableChangeSet with a key does only remove items once

### ISSUE THREAD

**Issue by Peter-B-** [RolandPheasant/DynamicData#187]
I believe I have found a bug in the ToObservableChangeSet operator.

It seems that objects are removed ony once if the expireafter operator is specified. This affects only the overload with a key.

Since the problem is hard to explain, I added some Unit Tests to a branch here:

https://github.com/Peter-B-/DynamicData/tree/ExpireAfterBug

The unit test called ExpireAfterTimeDynamicWithKey fails and shows the behaviour.

I also creaded an LinqPad script to see the bug in action:

http://share.linqpad.net/d33j3u.linq

In this query, new objects should be added every 0.1 seconds and be removed after 1 second. The count should never exceed 10 (or maybe 11). But you can see, that only one element is removed and from then on the count continues to grow.

I tried to find a solution to the problem, but it seems I am not fluent enough with RX to fix that.

**Comment by jholzer** [comment]
Same issue here! Fix would be highly appreciated...
