### ISSUE TITLE
CountChanged not working on SourceCache

### ISSUE THREAD

**Issue by andrewalex** [RolandPheasant/DynamicData#188]
I seem to be struggling getting SourceCache CountChanged to properly report

A simple example:

```
	public static void Main()
	{
		SourceCache<string, string> sc = new SourceCache<string, string>(x => x);
		
		sc.CountChanged.Subscribe(x => Console.WriteLine("sub" + x));
		sc.AddOrUpdate("1");sc.AddOrUpdate("2");sc.AddOrUpdate("3");sc.AddOrUpdate("4");
		Console.WriteLine(sc.Count);
		Console.WriteLine("Done");
	}

```

**Comment by RolandPheasant** [comment]
The fix has been deployed to Nuget  v6.7.1

**Comment by SchwabenProgger** [comment]
Current Nuget v6.8.0.* contains a similar error-scenario when using this code:

            var sc = new SourceCache<string, string>(x => x);
            sc.Connect().Count().Subscribe(x => Console.WriteLine("sub" + x));
            sc.AddOrUpdate("1"); sc.AddOrUpdate("2"); sc.AddOrUpdate("3"); sc.AddOrUpdate("4");
            Console.WriteLine(sc.Count);
            Console.WriteLine("Done");

**Comment by RolandPheasant** [comment]
Have you added the aggregation namespace:

```using DynamicData.Aggregation;```

**Comment by SchwabenProgger** [comment]
No, intellisense suggested this namespace first:

using System.Reactive.Linq;

Thank you - it works using DynamicData.Aggregation namespace.
