### ISSUE TITLE
ISourceCache<T, key> AddOrUpdate performance

### ISSUE THREAD

**Issue by sks2141** [RolandPheasant/DynamicData#189]
Hi Roland,

Thanks for putting up an amazing library. I have been using your library for one of our applications. 

I noticed that the performance of sourceCache<T, key>.AddOrUpdate (even with batch editing example) deteriorates when the underlying  T elements have a deep object footprint (such as properties with list of other objects etc.). As a result, when consuming updates, the new prototyped client falls behind the current one (definitely not a good spot to be on).

Do you know if there is any good way to boost the performance of adding or updating the cache?

Thanks!

**Comment by RolandPheasant** [comment]
The answer to the question of performance is always entirely contextual. It depends on so any factors and there can never be a single answer to the question  of what is the best solution.

The very first thing I would look at would be where is the bottleneck?  Is it the cache of is it consumers slowing things down? Also what is slow? How is that measured ?

**Comment by sks2141** [comment]
While debugging, I noticed that the line:
cache.AddOrUpdate(T) takes around 3-5 seconds to complete (or more, per object). The underlying object hosts a list of other objects (in property). 

For example, one of my tests, I noticed it took around 7 minutes to load 56k records in-memory. I ran your example (Dyanmic.Trader), increasing the number of trades to 100k (which was really quick to update). When i reduced the payload size (of T), the same tests took around 2 minutes to load 56k records.

I am assuming that the performance of sourceCache.AddOrUpdate is based on how bloated the underlying object is. If it is lightweight, its quick; else there is a time penalty.

**Comment by RolandPheasant** [comment]
That is awful, but it is not the cache.I just run this code:

```
    public class QuickAndDirtyPerformanceMeasure
    {
        private static readonly Person[] _people = Enumerable.Range(1, 56_000).Select(i => new Person($"Name {i}", i)).ToArray();
        private readonly SourceCache<Person, string> _peopleCache = new SourceCache<Person, string>(p=> p.Name);

        [Fact]
        public void AddLotsOfItems()
        {
            _peopleCache.AddOrUpdate(_people);
        }
    }
```

and here is the result when running in a unit test runner

![image](https://user-images.githubusercontent.com/9879866/50028503-ca380f80-ffe7-11e8-9c54-6e18d6d120c1.png)

Which is cannot explain the why your code is taking so long.

A very quick means of checking performance is to add break points like this:

![image](https://user-images.githubusercontent.com/9879866/50028810-c3f66300-ffe8-11e8-8c79-f5373edbd49e.png)

as brute force perf measures are perfectly valid. The great advantage of this strategy is as a dev you get a good idea of where is issue lies very quickly. It is not an exact metric and in many ways is laughable but it gives an instant guideline of what should be further looked into

**Comment by sks2141** [comment]
Roland - Thanks for the reply. You're correct - the issue is not related to sourceCache.AddOrUpdate.

I swapped up the source cache with a custom implementation and noticed that the issue is related to a slower consuming view. Minimizing the payload does help a little, but not by much.
