### ISSUE TITLE
Aggregation operators are not reevaluated on refresh

### ISSUE THREAD

**Issue by euhics** [RolandPheasant/DynamicData#192]
Hi,

I'm trying to use AutoRefresh and Sum together, but doesn't reevaluate the refreshed value. It would be an elegant and efficient way to do it. Is there another similar way ?
```C#
sourceCache
	.Connect()
	.AutoRefresh(x => x.SomeValue, changeSetBuffer: TimeSpan.FromMilliseconds(100), scheduler: UIScheduler)
	.Sum((MyObj obj) => obj.SomeValue) // Doesn't update on refresh
	.Subscribe(sum => ...)
```

Thank you.
I have just started using DynamicData after upgrading ReactiveUI and I really love it, thank you for all your work !

**Comment by euhics** [comment]
I've found the answer to my question.
A Refresh change doesn't have the previous item value, only an Update does.

So I change my code to this
```
sourceCache
	.Connect()
	.AutoRefresh(x => x.SomeValue, changeSetBuffer: TimeSpan.FromMilliseconds(100), scheduler: UIScheduler)
	.Transform(x => x.SomeValue, transformOnRefresh: true)
	.Sum(value => value)
	.Subscribe(sum => ...)
```
As Transform will perform a real update.

**Comment by RolandPheasant** [comment]
There is a limitation to the aggregation operator. When I originally wrote them I made them as light weight and were not programmed to subscribe to refresh notifications.

I will enable this at some point. At least for now, you have found a solution.
