### ISSUE TITLE
"Changing" events: before the actual change

### ISSUE THREAD

**Issue by Wouterdek** [RolandPheasant/DynamicData#194]
In the old ReactiveUI lists system, there was an interface called [`INotifyCollectionChanging`](https://reactiveui.net/api/reactiveui/inotifycollectionchanging/) which I found really useful.
It allowed you to preview changes to the list/collection before they were actually made through a separate observable. For example: upon calling `list.Add("A")`, observers would get a BeforeAdd notification with the item to be added before it was actually added. I found this really useful for managing the order of observers handling the change and maintaining invariants over the items in the list.

A quick scan through the source code seems to show that the biggest hurdle is that `ChangeAwareList` produces the set of changes only after they have already been made. This could be resolved on a higher level (ReaderWriter or SourceList) by making it a two stage process:  
First create a copy of the list (`_data`), apply the update action on the copy, push the resulting change set to the preview subject, then swap the updated copy with the old list, and finally push the same change set to the regular change subject. 
This allows observers of the preview observable to view the pending changes and view (but not write to) the old list state. The disadvantage would be that any edit of the list requires a copy of the list. However, accessing `Items` currently already requires a copy. Additionally, many usecases have small lists or few writes and I feel like the trade-off would be worth it. This could also be optimized by skipping the copy if there aren't any observers of the preview observable. Another option would be to have this behaviour in a specific subclass to make the trade-off more explicit.

Is there anything I've missed? Is there any reason, other than development time, that this isn't included? I would be willing to look into this next month and make a PR, but if you see fundamental problems or feel like this would not make a good contribution I'd rather save my time :)

**Comment by RolandPheasant** [comment]
What you say makes sense and the key to the implementation is to ensure there is no performance penalty when preview change is not subscribed to.

Perhaps the easiest way to do it would be to add a preview observable to source list / cache which provides an object which holds the change set  and a cancel property or method.

The data source can fire the observable and if a consumer sets cancel to true. On the face of it this should be easy to implement. However we may need to consider what would happen if there are multiple observers of the preview or consumers which use observeon.

The only reason I have never implemented this is that it has never been asked for. Also a PR would be welcomed
