### ISSUE TITLE
Create dynamic Or combiner

### ISSUE THREAD

**Issue by bradphelan** [RolandPheasant/DynamicData#20]
I've had a hack at it. It seems to work but looks very inefficient.
	
	        public static IObservable<IChangeSet<T>> Or<T>
	        (IObservable<IChangeSet<SourceList<T>>> observable)
	        {
	            var sl = new SourceList<T>();
	            var foo = observable
	                .ToCollection()
	                .Select
	                (list => list.Count != 0 ? list.Select(l => l.Connect())
	                             .Aggregate((a, b) => a.Or(b))
	                             .ToCollection()
	                             : Observable.Return(ImmutableList<T>.Empty)
	                             
	                             )
	                .Switch();
	
	            var d = foo
	                .Subscribe
	                (b =>
	                 {
	                     sl.Edit
	                         (e =>
	                          {
	                              e.Clear();
	                              e.AddRange(b);
	                          });
	
	                 });
	
	            return Observable.Using(()=>d,o=> sl.Connect());
	        }

**Comment by RolandPheasant** [comment]
@bradphelan I just published the official And, Or, Xor and Except operators for the observable list!

I have been so busy with my latest project see [Tail Blazer](https://github.com/RolandPheasant/TailBlazer) that I have yet to make any anouncements so sorry for any inconvenience.

You need to install this version [DynamicData 4.3.1.1090](https://www.nuget.org/packages/DynamicData/4.3.1.1090)

Then you can do this:
```
var a = new SourceList<int>();
var b = new SourceList<int>();
var c = new SourceList<int>();

//a logical OR
var d = a.Connect().Or(b.Connect()).Or(c.Connect()).AsObservableList();

//a logical AND
var d = a.Connect().And(b.Connect()).And(c.Connect()).AsObservableList();

//same syntax for Xor and Except
```

What you cannot do is dynamically add and remove lists from these collection operators. I will implement that in version 4.4.

**Comment by bradphelan** [comment]
I actually need the dynamic one.  I have something line a set of nested 3D
view models.  They can all generate primitives that can be drawn on the
screen.  The number of components changes and the number of primitives that
each component generates can change.  I'd like to flatten that to an
IObservableList<IPrimitive> from which I can add and remove them from the
render engine.

I'll take a look again tomorrow and see if I can figure it out.

**Comment by RolandPheasant** [comment]
The key complexity is ensuring that items are removed when an observable is removed from the dynamic Or.  The difficulty in doing it in the framework is an item can be in one or more lists so ref counts have to be track to know.

If your version is is not quite working for you I suggest you take a look at this [Combiner,cs](https://github.com/RolandPheasant/DynamicData/blob/master/DynamicData/List/Internal/Combiner.cs), grab the source code and adapt it locally (or do your own dynamic data build).  The key change is intead of the following constructor

```
  public Combiner([NotNull] List<IObservable<IChangeSet<T>>> source, CombineOperator type)
```
you would need this 
```
  public Combiner([NotNull] IObservableList<IObservable<IChangeSet<T>>> source, CombineOperator type)
```
In which case the only extra coding change would be to track items being added and removed from the source observable list.

I can do this myself soon buy alas I am committed to so other stuff for at least a week.  I could however do it in about 2 weeks.

**Comment by bradphelan** [comment]
Ok I'll take a peek tomorrow. Thanks for the ideas on the reference
tracking.

On another topic. I'm not convinced that Connect should return

IObservable<ChangeSet>

as it tries to implement two Monads and thus you have had to use other
names like Transform and TransformMany. Feels to me that
IObservable<ChangeSet> is an implementation detail that should be hidden
inside an IComposableList<T> which should support standard LINQ methods.

IComposableList<T> ( Does not implement IEnumerable<T> )

   - Items : IEnumerable<T>
   - List : IList<T>
   - Select<T,U>( Func<T,U> selector) : IComposableList<U>
   - SelectMany<T,U>(Func<T,IComposableList<U>>) : IComposableList<U>
   - Where( Func<T,bool> predicate) : IComposableList<U>


Then we could do

var source = new SourceList<double>();

IComposableList<double> target =
                   from s in source
                   select Math.Sin(s)

Just an idea.

**Comment by RolandPheasant** [comment]
@bradphelan it's been a long time but I have finally got around to nailing this one. From v4.6 onwards you can dynamically apply a logical operator

```cs
var list1 = new SourceList<int>();
var list2 = new SourceList<int>();
var list3  = new SourceList<int>();
	
var combined = new SourceList<ISourceList<int>>();

//child lists can be added or removed any time
combined.Add(list1);
combined.Add(list2);
combined.Add(list3);

//The operators look after themselves 
var inAll = combined.And();
var inAny = combined.Or();
var inOnlyOne= combined.Xor();
var inFirstAndNotAnyOther = combined.Except();
```

The initial code works for an observable list. I will implement it for an observable cache
