### ISSUE TITLE
Create OnItemAdded callback

### ISSUE THREAD

**Issue by bradphelan** [RolandPheasant/DynamicData#21]
There is OnItemRemoved but no OnItemAdded. I find that I sometime have to do some work when something is added to the collection. My implementation is.

        internal sealed class OnBeingAdded<T>
        {
            private readonly List<T> _items = new List<T>();
            private readonly IObservable<IChangeSet<T>> _source;
            private readonly Action<T> _callback;

            public OnBeingAdded(IObservable<IChangeSet<T>> source, Action<T> callback)
            {
                if (source == null)
                    throw new ArgumentNullException("source");
                if (callback == null)
                    throw new ArgumentNullException("callback");
                _source = source;
                _callback = callback;
            }

            public IObservable<IChangeSet<T>> Run()
            {
                return Observable.Create((Func<IObserver<IChangeSet<T>>, IDisposable>)(observer =>
               {
                   var subscriber = _source.Do(RegisterForRemoval, observer.OnError).SubscribeSafe(observer);
                   return Disposable.Create(() =>
                                            {
                                                subscriber.Dispose();
                                                _items.ForEach<T>(t => _callback(t));
                                                _items.Clear();
                                            });
               }));
            }

            private void RegisterForRemoval(IChangeSet<T> changes)
            {
                changes.ForEach(change =>
              {
                  switch (change.Reason)
                  {
                      case ListChangeReason.Add:
                          _callback(change.Item.Current);
                          break;
                      case ListChangeReason.AddRange:
                          change.Range.ForEach(_callback);
                          break;
                      case ListChangeReason.Replace:
                          _callback(change.Item.Current);
                          break;
                      case ListChangeReason.Remove:
                          break;
                      case ListChangeReason.RemoveRange:
                          break;
                      case ListChangeReason.Moved:
                          break;
                      case ListChangeReason.Clear:
                          break;
                      default:
                          throw new ArgumentOutOfRangeException();
                  }
              });
                _items.Clone(changes);
            }
        }

        public static IObservable<IChangeSet<T>> OnItemAdded<T>
            (this IObservable<IChangeSet<T>> source,
             Action<T> addAction)
        {
            if (source == null)
                throw new ArgumentNullException("source");
            if (addAction == null)
                throw new ArgumentNullException("addAction");
            return new OnBeingAdded<T>(source, addAction).Run();
        }

**Comment by RolandPheasant** [comment]
Do you want to add this one your self and do a pull request?

**Comment by RolandPheasant** [comment]
@bradphelan 

Alternatively perhaps ...WhereChangeReasonsAre(...) operator would do the job for you.

**Comment by RolandPheasant** [comment]
I have adapted the code and it will in release #4.6
