### ISSUE TITLE
Extension method DisposeMany seems not to be thread safe 

### ISSUE THREAD

**Issue by huemer2** [RolandPheasant/DynamicData#212]
Hello,

i am having troubles when disposing a subscription to a cache where Transform and DisposeMany are involved and the cache is updated by a different thread.

As soon as I'm trying to dispose the subscription via MainThread while the background task is updating the cache simultaneously an InvalidOperationException is thrown due to a changed enumeration:

**Collection was modified; enumeration operation may not execute.**
=> System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)\r\n   bei System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()\r\n   bei DynamicData.Kernel.EnumerableEx.ForEach[T](IEnumerable`1 source, Action`1 action) in /_/DynamicData/Kernel/EnumerableEx.cs:Zeile 108.\r\n   bei DynamicData.Cache.Internal.DisposeMany`2.<>c__DisplayClass3_0.<Run>b__2() in /_/DynamicData/Cache/Internal/DisposeMany.cs:Zeile 32...

I attached my sample project which produces the exception nearly every time the "ReSubscribe" button is pressed. I have to mention, that i added a Sleep of 1ms to the Dispose method of the transformed objects to simulate production behaviour.
[WpfApp2.zip](https://github.com/RolandPheasant/DynamicData/files/2961390/WpfApp2.zip)

The sample also contains a workaround with a lockobject used by the Synchronize extension method and is locked while disposing the subscription. This workaround is disabled by the commented Line 83. If this line is uncommented, then the exception does not occur.

So my questions are...
1) am I using your extension methods wrong? 
2) Is it possible to fix this issue in the DynamicData code? 
My educated guess is to reorder these lines (31-33) in DisposeMany class:
` cache.Items.ForEach(t => _removeAction(t));
 cache.Clear();
 subscriber.Dispose();`
to
`subscriber.Dispose(); cache.Items.ForEach(t => _removeAction(t));
                    cache.Clear();` 
so first the subscription is disposed and therefore no OnNext's arrive anymore and then the cache.Items are iterated. 
3) Or do i have to implemented locking by myself via the suggested lock mechanism in the samplecode.

kind regards
christoph

**Comment by RolandPheasant** [comment]
This is a model problem report. Thanks for taking to trouble not only to reproduce but the issue but to also diagnose the problem.

Your suggested fix works but perhaps a better solution would be to move `DisposeMany` after `Bind` as this will dispose on the dispatcher which is single threaded and therefore intrinsically synchronised. Also it is always better to dispose an object when there is no longer anything using it.  

The real problem as you have identified is inside `DisposeMany`. It needs to be fixed.  I wrote this operator many years ago and it is the first time the issue has been observed. However looking at the code, the dispose method is clearly an issue. The code below is a copy of the code which I have annotated to illustrate the changes I will make.

```cs
return Observable.Create<IChangeSet<TObject, TKey>>(observer =>
{
    var cache = new Cache<TObject, TKey>();
    var subscriber = _source
        //need sync here
        .Do(changes => RegisterForRemoval(changes, cache), observer.OnError)
        .SubscribeSafe(observer);

    return Disposable.Create(() =>
    {
        //need sync here
        cache.Items.ForEach(t => _removeAction(t));
        cache.Clear();
        //this should be called before _removeAction
        subscriber.Dispose();
   });
});
```

**Comment by huemer2** [comment]
Thanks for your immediate response and fix! 
And in general, thanks for your libary at all as it fits perfectly to my requirements. 

I'am looking forward to a new nuget version soon :)
