### ISSUE TITLE
Filter method without filter parameters does not make sense

### ISSUE THREAD

**Issue by Didovgopoly** [RolandPheasant/DynamicData#219]
Hi, I came across the method 

```
Filter<TObject, TKey>([NotNull] this IObservable<IChangeSet<TObject, TKey>> source,
    [NotNull] IObservable<Unit> reapplyFilter)
```

And i don't understand the usage. It looks like it will always skip all the elements since we don't have the filter. The red test to show the behavior.

```
[Fact]
public void FiltersSomething()
{
    var source = new SourceCache<Person, string>(p => p.Name);

    var reapplyFilter = new Subject<Unit>();
    var results = source.Connect().Filter(reapplyFilter).AsAggregator();
    
    source.AddOrUpdate(new Person("Mike", 10));
    
    reapplyFilter.OnNext(Unit.Default);
    results.Messages.Count.Should().Be(1, "Should be 1 updates");
    results.Data.Count.Should().Be(1, "Should have 1 element");
}
```

**Comment by RolandPheasant** [comment]
If you add or update, filtering is automatic.  Reapply filter is an option which can be used when filtering on mutable values.  Also in dd for performance reasons, empty change sets are never reported.

In your example, nothing has changed so there is no notification even though you explicitly re-applied the filter.

In recommend you down load this [DynamicData Snippets](https://github.com/RolandPheasant/DynamicData.Snippets) where there are some examples of dd filtering + unit tests to illustrate expectations
