### ISSUE TITLE
AutoRefresh + Transform + AsObservableList does not work as expected

### ISSUE THREAD

**Issue by Wouterdek** [RolandPheasant/DynamicData#220]
The following test fails on the assertion line:

```csharp
public void TestRefreshTransformAsList()
{
    SourceList<Example> list = new SourceList<Example>();
    var valueList = list.Connect()
        .AutoRefresh(e => e.Value)
        .Transform(e => e.Value, true)
        .AsObservableList();

    var obj = new Example {Value = 0};
    list.Add(obj);
    obj.Value = 1;
    Assert.AreEqual(valueList.Items.First(), 1); //valueList contains 0 instead of 1 here
}
```

Autorefresh correctly detects the change in value and pushes a `refresh` change.
Transform receives this and [updates its internal list](https://github.com/RolandPheasant/DynamicData/blob/99969e93f723c89d6810096192b741c389005e7a/DynamicData/List/Internal/Transformer.cs#L116) using [`ChangeAwareList.Refresh`](https://github.com/RolandPheasant/DynamicData/blob/99969e93f723c89d6810096192b741c389005e7a/DynamicData/List/ChangeAwareList.cs#L206).

In the final step, the refresh update arrives at the `SourceList<int>` (valueList) that should be updated. The changes are applied using [ListEx.Clone](https://github.com/RolandPheasant/DynamicData/blob/99969e93f723c89d6810096192b741c389005e7a/DynamicData/List/ListEx.cs#L52) and here stuff goes wrong. The change is a `Refresh` change, and the list is a `ChangeAwareList` so `RefreshAt` is used instead of `RemoveAt` and `Insert`. However, `RefreshAt` does not update the data in the list so the result is wrong.

**Comment by RolandPheasant** [comment]
That's a good bit of analysis. Have you thought of a solution?

**Comment by Wouterdek** [comment]
I'm not entirely sure to be honest. Maybe refresh changes that go through a transform should come out as a replace change if the result of the transformation has changed?

**Comment by RolandPheasant** [comment]
The issue is in the transformer class.  The item is transformed, but a refresh change is sent whereas it should be a replace.

The fix is easy but some other unit tests break as a result.

**Comment by Wouterdek** [comment]
Great work, thanks!
