### ISSUE TITLE
How to get a list of changes

### ISSUE THREAD

**Issue by ben1628** [RolandPheasant/DynamicData#227]
New to DynamicData.

I have a grid that are populated by dynamic data, everything seems to be working.  When I make changes to a field, I will get

 _myList.Connect()
                //.QueryWhenChanged()
                .WhenAnyPropertyChanged()
                .Subscribe(t =>
                {

                    Debug.Print(t.Symbol);
                    Debug.Print(t.SymbolID.ToString());

                }
                );

which is great.  

However, when a user click a SAVE button to save all the changes, I was hoping I can do something like

 OKCmd = ReactiveCommand.Create(() =>
            {
                // Status = $"{EnteredText} is saved.";
                var change = _myList
                    .Connect()
                    .ToObservableChangeSet()
                    .ToCollection();
                //    .QueryWhenChanged();
                // Save a list of changes to database  
                // var changeSet = change .ToObservableChangeSet().ToCollection().ToList();
                //var person = _myList.Connect().WhenAnyPropertyChanged();

                //    );
            }
            );

changeSet to me a list of changes and also the new items, but I don't seem to be able to do it.

**Comment by worldbeater** [comment]
Probably you could do somewhat like:
```cs
// Declare a collection containing your items.
ReadOnlyObservableCollection<Item> _items;

// This is how you update the collection declared above.
connectable
    .Connect()
    .WhenAnyPropertyChanged()
    .Bind(out _items)
    .Subscribe();

// Access all items in the Save command!
Save = ReactiveCommand.CreateFromTask(async () => {
  await storage.Save(_items);
});
```
If your are writing unit tests. then the following code could be a way to go:
```cs
var aggregator = connectable.Connect().AsAggregator();
aggregator.Data.Count // items count
aggregator.Data.Items // items themselves
```
Worth reading [ReactiveUI Collections Handbook](https://reactiveui.net/docs/handbook/collections/) btw.

**Comment by ben1628** [comment]
OK,  so ToObservableChangeSet() won't give me a list of changes?

So I need to save a copy of what's changed and save it later, nothing magical.

**Comment by worldbeater** [comment]
`ToObservableChangeSet()` will definitely give you a list of changes, but it will be lazily evaluated, so keeping a separate collection with changed items and updating it using `Bind` would be a better idea IMHO. Btw it would be even better to ask questions on StackOverflow or in [ReactiveUI Slack](https://reactiveui.net/slack) (DynamicData channel). Folks use Github Issues primarily for bug reports or feature requests, and it is highly likely that someone will help if you join [Slack](https://reactiveui.net/slack) and ask there.
