### ISSUE TITLE
Publish symbols with nuget package.

### ISSUE THREAD

**Issue by ButchersBoy** [RolandPheasant/DynamicData#23]
...would greatly assist with debugging.

**Comment by RolandPheasant** [comment]
Symbols are now published. To do this correctly I had to split dynamic data into 2 packages

[DynamicData (4.4 beta)](https://www.nuget.org/packages/DynamicData/4.4.0.1110-beta)
[DynamicData.Plinq (4.4 beta)](https://www.nuget.org/packages/DynamicData.Plinq/4.4.0.1110-beta) 

where plinq extends dynamic data and contains net4.5 specifc functionality.

@ButchersBoy you will need to install DynamicData.Plinq in Monaco

**Comment by ButchersBoy** [comment]
:+1:
