### ISSUE TITLE
Re-binding to existing collection doesn't reset if SourceCache is empty

### ISSUE THREAD

**Issue by TyBarthel** [RolandPheasant/DynamicData#232]
The scenario I ran into seems to be potentially related to #29 and #169 where a SourceCache doesn't emit an empty change set when it's empty and existing collection re-subscribes/binds.  This prevents the collections using "Bind" to not be reset when setting up a new subscription leaving stale items.  Everything works as planned when there are 1 or more items in the SourceCache because a change set gets emitted and the collection is reset and items added.

The same issue can be reproduced using the Bind with the out ReadOnlyObservableCollection parameter.

The easy workaround for the issue is to use StartWithEmpty (seen below commented out in the unit test).

Psueo-code:
Add item to SourceCache
Bind to ObservableCollection
*ObservableCollection has 1 item*
Dispose subscription 
Remove item from SourceCache
*SourceCache has 0 items*
Bind to ObservableCollection
*ObservableCollection still has 1 item*

The scenario stems from mobile development where subscribing, unsubscribing, and re-subscribing is common during activations and deactivations of views/view models.

Unit test reproducing the scenario:
```
using DynamicData.Binding;
using FluentAssertions;
using System;
using System.Reactive.Linq;
using Xunit;

namespace DynamicData.Tests
{
    public class SourceCacheTestFixture
    {
        private readonly SourceCache<Item, Guid> _sourceCache;
        private readonly IObservableCache<Item, Guid> _observableCache;
        private readonly ObservableCollectionExtended<Item> _collection;

        public SourceCacheTestFixture()
        {
            _sourceCache = new SourceCache<Item, Guid>(x => x.Id);
            _observableCache = _sourceCache.Connect().AsObservableCache();
            _collection = new ObservableCollectionExtended<Item>();
        }

        [Fact]
        public void ReactivateTest()
        {
            var item1 = new Item();
            var item2 = new Item();
            var item3 = new Item();
            var item4 = new Item();

            _sourceCache.AddOrUpdate(item1);
            _sourceCache.AddOrUpdate(item2);
            _sourceCache.AddOrUpdate(item3);
            _sourceCache.AddOrUpdate(item4);

            // All 4 items exist in ObservableCollection and SourceCache after subscription
            // Then simulate "deactivation" of a view (i.e. mobile)
            var subscription = SetupSubscription();
            _sourceCache.Count.Should().Be(4);
            _collection.Count.Should().Be(4);
            subscription.Dispose();

            _sourceCache.Remove(item1);

            // Now 3 items exist in ObservableCollection and SourceCache after subscription simulating re-activation
            // Then again "deactivate"
            subscription = SetupSubscription();
            _sourceCache.Count.Should().Be(3);
            _collection.Count.Should().Be(3);
            subscription.Dispose();

            _sourceCache.Remove(item2);
            _sourceCache.Remove(item3);
            _sourceCache.Remove(item4);

            // Now 3 items exist in OservableCollection and 0 in the SourceCache
            // Unless you "StartWithEmpty" to push an empty change set on initial bind
            subscription = SetupSubscription();
            _sourceCache.Count.Should().Be(0);
            _collection.Count.Should().Be(0);
            subscription.Dispose();
        }

        IDisposable SetupSubscription()
        {
            return _observableCache
                .Connect()
                //.StartWithEmpty()
                .Bind(_collection)
                .Subscribe();
        }

        class Item
        {
            public Guid Id { get; } = Guid.NewGuid();
        }
    }
}
```

**Comment by RolandPheasant** [comment]
This is the intended behaviour. There is nothing in dynamic data which will intentionally clear an observable collection when a subscription is disposed of.  It is a coincidence upon a re-subscribe that a reset is emitted.  The work around for your use case is perfectly legitimate.

Two other alternatives would be to:

Use a dispose action which clears the cache when the subscription is disposed of.
Make use of dd's overload of switch statement - example [here](https://github.com/RolandPheasant/DynamicData.Snippets/tree/master/DynamicData.Snippets/Switch)
