### ISSUE TITLE
ChangeAwareCache crash when filtering

### ISSUE THREAD

**Issue by lummoj** [RolandPheasant/DynamicData#233]
We are running into an issue with the Filter() operator intermittently causing crashes. See stack trace below:
```
System.ArgumentException: An item with the same key has already been added.
  at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
  at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
  at DynamicData.ChangeAwareCache`2.Add(TObject item, TKey key) in /_/DynamicData/Cache/ChangeAwareCache.cs:line 62
  at DynamicData.Cache.Internal.FilterEx.FilterChanges[TObject,TKey](ChangeAwareCache`2 cache, IChangeSet`2 changes, Func`2 predicate) in /_/DynamicData/Cache/Internal/FilterEx.cs:line 49
  at DynamicData.Cache.Internal.DynamicFilter`2.<>c__DisplayClass4_0.<Run>b__3(IChangeSet`2 changes) in /_/DynamicData/Cache/Internal/DynamicFilter.cs:line 52
  at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 39
```

It seems to be caused by the value already being in the cache even when ChangeReason is Add as in FilterEx.cs:45 it calls `cache.Add(current, key);` rather than `cache.AddOrUpdate(current, key);` and we get an exception.

I'm trying to understand the sequence of events in order to explain why this might be happening. The current expression is quite complex using `MergeMany()` and `AutoRefresh()` before `Filter()` and I'm yet to reproduce it using something simple I can share. Initially I introduced more synchronization and locking thinking that might be the issue but that did not seem to help. 

I'm assuming that somewhere along the line we either have two Adds for the same item or an Update / Refresh appearing before an Add for the same item. Any ideas about where to go from here? Switching FilterEx.cs to use `AddOrUpdate` instead of `Add` for `ChangeReason.Add` is a quick fix but I'm not sure this is the right way to go.

**Comment by lummoj** [comment]
I've come up with a fairly simple reproduction:

```public class SimpleClass
    {
        public SimpleClass(int key)
        {
            Key = key;
        }

        public int Key { get; }
    }

    [TestClass]
    public class DynamicDataTest
    {
        [TestMethod]
        public void FilterException()
        {
            var cache1 = new SourceCache<SimpleClass, int>(c => c.Key);

            cache1
                .Connect()
                .Merge(cache1.Connect())
                .Filter(c => c.Key == 7)
                .Subscribe(s =>
                {
                    Console.WriteLine("Exception thrown before we get here");
                });

            var item = new SimpleClass(7);
            
            cache1.AddOrUpdate(item);
        }
    }```

I started off with two caches both containing the same item, this is not strictly necessary as you can just merge with yourself. Not particularly realistic but in our scenario we do have the same items in different caches.

**Comment by RolandPheasant** [comment]
Thanks for such a clear diagnosis to the problem which you have encountered. This will make the fix easy which will be simply to use AddOrUpdate

**Comment by lummoj** [comment]
Thanks for accepting the PR Roland.
Any idea when you're planning to do another official release?
Would be great to be able to switch back to the NuGet package.

**Comment by RolandPheasant** [comment]
I should get time in the next few days
