### ISSUE TITLE
Difference between SourceCache and SourceList

### ISSUE THREAD

**Issue by ben1628** [RolandPheasant/DynamicData#237]
I read the readme over and over again.  Is this a correct understanding?

With SourceCache, I can add or update SourceCache.  With SourceList, I cannot add, I can only update?

Can someone give me a simple example of creating a SourceCache and subscribe to it so it will add a new item a grid in UI.  I always get a cross thread error.

Really like to use dynamicData, but get stuck here. Please help.

**Comment by MendelMonteiro** [comment]
You can find a good description here:
https://dynamic-data.org/2015/08/12/observable-cache-at-a-glance/
