### ISSUE TITLE
Suggestion: Way to "Bind" ICollection<T> with SourceCache/SourceList

### ISSUE THREAD

**Issue by StefanDoubleU** [RolandPheasant/DynamicData#27]
Hello Roland,

first of all, DynamicData is great!
I currently have the need for maintaining a list (its actually internal settings representation) but also using a SourceCache for propagating changes and data to the rest of the application. Think of it as a settings service in an application.

It would be great to have a builtin way to reflect add and remove changes to a list, like .Bind()

With best regards,
Stefan

**Comment by RolandPheasant** [comment]
If I understand correctly then that should be easy as the code already does all that behind the scenes

**Comment by StefanDoubleU** [comment]
Exactly. Actually its very similar to Bind, but no IObservableCollection.

**Comment by RolandPheasant** [comment]
Exactly. The main consideration would be thread safety

**Comment by RolandPheasant** [comment]
Does .ToCollection() suit your purposes?

**Comment by StefanDoubleU** [comment]
Not really. Actually I need to maintain a second list besides the SourceCache, which has initial values and the reference should not change.

**Comment by RolandPheasant** [comment]
Ok. Should be able to do it soon.

**Comment by StefanDoubleU** [comment]
Great! Have a nice weekend.

**Comment by RolandPheasant** [comment]
I have introduced clone methods to achieve this.

```
var collection = new Collection<Person>();
var source = new SourceCache<Person, string>(p => p.Name);
var cloner = _source.Connect().Clone(_collection) .Subscribe();
```

You will have to take control of thread safety your self since you could be consuming the collection at the same time as the cloner.

I have also made changes to the nuget package and moved some specific dot net 4.5 features to a new package. Dynamic data is now in 2 packages.

[DynamicData (4.4 beta)](https://www.nuget.org/packages/DynamicData/4.4.0.1110-beta)
[DynamicData.Plinq (4.4 beta)](https://www.nuget.org/packages/DynamicData.Plinq/4.4.0.1110-beta) 

If you are targeting dotNet 4.5 you should install  the Plinq package

**Comment by RolandPheasant** [comment]
@StefanDoubleU let me know whether this new method works

**Comment by StefanDoubleU** [comment]
Hey Roland, 

almost great. But what about initial values in the collection. With the provided example, The  SourceCache and the cloned collection differs by the initial values. 

```C#
var collection = new Collection<string> { "start value 1" , "start value 2" } ;
var source = new SourceCache<string, string>(p => p);
source.AddOrUpdate(collection);

var cloner = source
	.Connect()
	.Clone(collection)
	.Subscribe();	
	
source.AddOrUpdate("some added string");
source.AddOrUpdate("new string");

source.Items.Dump();
collection.Dump();
```

Result:
```
String[] (4 items)
start value 1 
start value 2 
some added string 
new string 


Collection<String> (6 items)
start value 1 
start value 2 
start value 1 
start value 2 
some added string 
new string 
```

Maybe a solution could be an overload with an IEqualityComparer for Clone().

Not quite sure... Any idea?

**Comment by RolandPheasant** [comment]
@StefanDoubleU I had forgotten about this! Not entirely sure what the best soluton is as dynamic data is based entirely on the SourceCace / SourceList being the golden data source.

I'll have a think
