### ISSUE TITLE
Confused ObservableList when merging to ObservableCollectionExtends

### ISSUE THREAD

**Issue by djb12** [RolandPheasant/DynamicData#28]
Hello Roland,

thank you for providing DynamicData which we use as a standard asset in our projects and which provides very elegant solutions for many bread-and-butter programming issues.

My team and me have discovered some unexpected behavior: When merging two observable collections and then adding and removing values, there is something strange going on. We created a small LinqPad-script that illustrates the issue.

`      var a = new ObservableCollectionExtended<int>();
	var b = new ObservableCollectionExtended<int>();
	
	Observable.Merge(
	a.ToObservableChangeSet(),
	b.ToObservableChangeSet())
		//		.AddKey(x => x.GetHashCode())
		.QueryWhenChanged(x => x.Dump())
		.Subscribe();

	a.Add(1);
	a.Add(2);
	b.Add(4);
	a.Remove(1);`

The result is as follows 

![image](https://cloud.githubusercontent.com/assets/8402329/13137376/e326662a-d620-11e5-9bf5-d1df0b606c7c.png)

When you uncomment the line .AddKey[...], the whole thing is converted to an ObservableCache and the elements are added and removed as expected so we assume it is an issue with ObservableList.

Best,
djb

**Comment by RolandPheasant** [comment]
I'll will replicate using your example when I finish work tonight.

Have you tried subscribing to exceptions?

Also have you tried the latest beta version?

**Comment by RolandPheasant** [comment]
Actually reading it again, you probably need the Or operator. Which correctly combines 2 lists.

BTW there is all and And,xor and except operator to merge lists.

**Comment by djb12** [comment]
Hello again Roland,

thank you for the quick answer. I had not realized that there actually was an OR operator for ObservableLists as well in the latest version of DynamicData.

Using OR works like a charm.

Thank you very much and keep up the good work!

**Comment by RolandPheasant** [comment]
You are more than welcome and I am happy that dynamic data is helping you with your work
