### ISSUE TITLE
issue sorting 

### ISSUE THREAD

**Issue by julesx** [RolandPheasant/DynamicData#3]
with the following cache connect

            _pageController = new PageController();
            _filterController = new FilterController<MyVm>(myobject => myobject.Id != "");
            _sortController = new SortController<MyVm>(SortExpressionComparer<MyVm>.Descending(t => t.Id));

            var mySubscription = MyCache.Connect()
                .Filter(_filterController)
                .Sort(_sortController)
                .Page(_pageController)
                .ObserveOnDispatcher() 
                .Bind(Items)
                .Subscribe(); 

calling the following has no effect

_sortController.Change(SortExpressionComparer<MyVm>.Ascending(t => t.Id));

if i remove the page controller OR if i create a new page request like so
            _pageController.Change(new PageRequest(1, 2));

then sorting works again. it looks like if you use a page controller without doing any paging the sorting just doesnt work.

Edit: It also appears that if you make the page the same size or greater than the number of elements, sorting doesnt work.

Edit: Add Some items to the cache
            MyCache.AddOrUpdate(new MyVm("1"));
            MyCache.AddOrUpdate(new MyVm("2"));
            MyCache.AddOrUpdate(new MyVm("3"));
            MyCache.AddOrUpdate(new MyVm("4"));

            _pageController.Change(new PageRequest(1, 3));
            _sortController.Change(SortExpressionComparer<MyVm>.Ascending(t => t.Id));

throws ArgumentOutOfRangeException. however a page size of 1 or 2 works fine.

**Comment by RolandPheasant** [comment]
I am taking a look at it right now

**Comment by julesx** [comment]
beta has resolved all of these issues

**Comment by RolandPheasant** [comment]
Excellent. I will merge the fix to the main branch tomorrow then close this issue

**Comment by RolandPheasant** [comment]
Published on main build now available Dynamic Data 3.3.0.1067
