### ISSUE TITLE
Error with .Convert().Sort()

### ISSUE THREAD

**Issue by Peter-B-** [RolandPheasant/DynamicData#30]
Hello

I have an issue with `Convert` followed by `Sort`. As soon as I remove an element of the underlying source, I get an exception:

`Current position cannot be found. The item is not in the collection`

The query is 

```
cache.Connect()
	.Convert(nr => new Container(nr)) 
	.Sort(SortExpressionComparer<Container>.Ascending(c => c.Nr))
	.Subscribe(x => x.Dump(), ex => ex.Dump());
```

Here you can find a LinqPad script as `.txt` file.
[Convert - Sort - Problem.txt](https://github.com/RolandPheasant/DynamicData/files/167278/Convert.-.Sort.-.Problem.txt)

I do not see that exception when I use `Transform` or `TransformSafe` instead of `Convert`. 
Is that by design? 
Is `Convert` the wrong method to use here?

Thanks a lot for any hint or explanation.

Greetings
Peter

**Comment by RolandPheasant** [comment]
Originally I intended the concert function to be akin to casting. However perhaps I should get rid of it and recommend using Transform.

**Comment by Peter-B-** [comment]
Thanks for your response. I already thought that I misused it.
