### ISSUE TITLE
Code formatting/style

### ISSUE THREAD

**Issue by MendelMonteiro** [RolandPheasant/DynamicData#36]
I've got a couple of suggestions, let me know if you agree and I'll create a pull request.

1. Only use tabs - no spaces for indentation
2. Don't use IEnumerable.ForEach, use foreach instead
3. Put switch break; statements inside the scope regions if present

Cheers

**Comment by RolandPheasant** [comment]
@MendelMonteiro it you think you could make the code cleaner the pleanse go for it and I will happily accept your contribution.
