### ISSUE TITLE
[Question] Connect to a bound list to create a "view on a view on a source" / "derived-derived collection"?

### ISSUE THREAD

**Issue by dsaf** [RolandPheasant/DynamicData#47]
My scenario:

1) there is a source list of domain entities;
2) that source list is used to produce a derived list of view models which have a property ```IsSelected``` since selection is a GUI concern;
3) how do I react to ```IsSelected``` property changes to create a "sub-derived" collection of selected view models?

Here is a working mixed ReactiveUI solution, which unfortunately has it's own known problems.

```csharp
private readonly ReactiveList<OrderViewModel> _items;
private readonly IReactiveDerivedList<OrderViewModel> _selectedItems;

orderProvider.Orders
    .Connect()
    .Transform(o => new OrderViewModel(o))
    .ObserveOnDispatcher()
    .Bind(_items)
    .DisposeMany()
    .Subscribe();

_selectedItems = _items.CreateDerivedCollection(x => x, x => x.IsSelected);
```

Is there any way to make it DynamicData-only maybe via ```WhenValueChanged```? So far I have discovered ```Clone``` which doesn't seem to be the best fit.

**Comment by RolandPheasant** [comment]
Use. Connect().FilterOnProperty(). 

That acts on objects which implement Inotifypropertychanged. It accepts the property and  a predicate as it's parameters

**Comment by dsaf** [comment]
To clarify: ```IsSelected``` is not present on ```Order``` and only present on ```OrderViewModel```.

Do you mean that it is possible to track the ```INotifyPropertyChanged``` objects generated via ```Transform``` on the fly without any intermediate ```SourceList```?

**Comment by RolandPheasant** [comment]
FilterOnProperty can be after the transform so it acts on the view model. 

If you want a filter of selected and a filter of not selected,  you can create a derived list of view model objects first,  then create multiple filtered derived lists.

**Comment by dsaf** [comment]
When you say ```derived``` do you mean ```SourceList``` or ```ObservableCollectionExtended```? Because I cannot use ReactiveUI's ```IReactiveDerivedList``` due to it's bugs.

**Comment by dsaf** [comment]
Ideally I want this:

```
private readonly SourceList<OrderViewModel> _items;
private readonly SourceList<OrderViewModel> _selectedItems;

orderProvider.Orders
    .Connect()
    .Transform(o => new OrderViewModel(o))
    .ObserveOnDispatcher()
    .Bind(_items)
    .DisposeMany()
    .Subscribe();

_items
    .Connect()
    .WhenValueChanged(x => x.IsSelected)
    .FilterOnProperty(x => x.IsSelected)
    .ObserveOnDispatcher()
    .Bind(_selectedItems)
    .DisposeMany()
    .Subscribe();
```

The last statement will not work because binding *to* a ```SourceList``` is not supported for understandable reasons.

**Comment by RolandPheasant** [comment]
This is easier than you realise. 

Remove whenvaluechanged as filter on property already monitors that. 

You can make as many derived lists as you want,  or make use of connect(). Publish()  to create multiple results from a single source

**Comment by RolandPheasant** [comment]
I will  not get a chance until next week but perhaps I should create a getting started project. 

This requirement would be the first example as I have had to help many people to do the same.

**Comment by dsaf** [comment]
I am sorry, I am not communicating the problem well enough.

> You can make as many derived lists as you want, or make use of connect(). Publish() to create multiple results from a single source

The problem is that I want to derive from a derived list. But derived lists don't support connecting.

**Comment by dsaf** [comment]
Level 1: Source
Level 2: Derived from Source adding a property
Level 3: Derived from Derived filtering on the added property

**Comment by dsaf** [comment]
So my only choice is moving the "property" to Source. But this is not clean, so I am trying to avoid it.

**Comment by RolandPheasant** [comment]
That's not what I mean.  I cannot properly type code now because I  am on a phone but heres some meta code:

Mybaselist = new sourcelist() 

Myvms = Mybaselist. Connect().transform(.. Tovm). AsObservableList() 

Myselected = Myvms. Connect(). FilterOnProperty(.. ).Bind(selectedoc).... 

MyNotselected = Myvms. Connect(). FilterOnProperty(.. ).Bind(notselectedoc).... 

You will need to enter the bind,  sort,  predicates, observe on etc but that will work

**Comment by RolandPheasant** [comment]
@dsaf I have created a working example which takes a domain object, transforms it into a view model and monitors selection. See this [DynamicData.Samplz](https://github.com/RolandPheasant/DynamicData.Samplz). You will need vs 2015 to build and run it.

![selectableitems](https://cloud.githubusercontent.com/assets/9879866/16322374/928d586c-399a-11e6-93c9-cd520f6da679.gif)

An further questions the best place to contact me is on [Dynamic Data Gitter](https://gitter.im/RolandPheasant/DynamicData)

**Comment by dsaf** [comment]
Thank you this is quite helpful! Sorry I did not reply, I was trying to create a stable release for tomorrow. At some point I started to feel like going reactive (in general) was a gamble from my side :), but it was OK in the end. A few other issues left, but that's a separate story.

**Comment by RolandPheasant** [comment]
No worries, feel free to ask questions but definitely better on the Gitter channel.

Once you are hooked by reactive, there is no turning back. It is not only the present but will increasingly dominate the future.

**Comment by dsaf** [comment]
Thank you.
