### ISSUE TITLE
getting a random item from a paged, filtered list

### ISSUE THREAD

**Issue by julesx** [RolandPheasant/DynamicData#5]
I have an ItemCache connected like so, where `Items` is an `OC<ItemVm>`

```
ItemCache.Connect()
                        .Filter(FilterController).Do(OnNext)
                        .Sort(SortController).Do(OnNext)
                        .Page(PageController).Do(OnNext)
                        .ObserveOnDispatcher()
                        .Do(changes => _pageParameters.Update(changes.Response))
                        .Bind(Items)
                        .Subscribe();
```

Here is my attempt at getting a random item. It is using `Items`

                var rInt = r.Next(0, Items.Count - 1);
                var randomItemVm = Items.Skip(rInt).Take(1).Single();

The problem is that `Items` only ever holds as many items as there are per page.  How can I pull a random item from `ItemCache` whether or not it is on the current page, keeping in mind that a filter has been applied?

**Comment by RolandPheasant** [comment]
if you want to get an item from the filtered result set do this

```csharp
// create a new filtred cache
var filteredCache = tradeService.All.Connect()
	.Filter(filterController)
	.AsObservableCache();

//load data from the filtered list
var dataLoader = filteredCache
	.Sort(SortController).Do(OnNext)
	.Page(PageController).Do(OnNext)
	.ObserveOnDispatcher()
	.Do(changes => _pageParameters.Update(changes.Response))
	.Bind(Items)
	.Subscribe();

//get a random item from the filtered.Items
var rInt = r.Next(0, filteredCache.Count - 1);
var item = filteredCache.Items.ElementAt(rInt);
```
The ```AsObservableCache()``` lines has created a new filtered cache. This is disposable so make you clean up after your  view model is finished with

**Comment by julesx** [comment]
so instead of connecting my items to sort, page, and filter all in one go, we split out the filter operation and expose the filtered cache to paging and sorting. that makes sense. however, going back to my example

```
            var filteredCache = ItemCache.Connect()
                .Filter(FilterController)
                .AsObservableCache();

            Connected = filteredCache
                        .Sort(SortController).Do(OnNext)
                        .Page(PageController).Do(OnNext)
                        .ObserveOnDispatcher()
                        .Do(changes => _pageParameters.Update(changes.Response))
                        .Bind(Items)
                        .Subscribe();
```

filteredCache.Sort does not resolve

**Comment by RolandPheasant** [comment]
oops 
```csharp
 Connected = filteredCache.Connect()
                        .Sort(SortController)
```

Also remember the dispose any connected items after use

**Comment by julesx** [comment]
Sweet!!!
