### ISSUE TITLE
Incompatible with Reactive v3.0.0.0

### ISSUE THREAD

**Issue by robsonj** [RolandPheasant/DynamicData#52]
Not really a bug. But unfortunately Reactive v3.0.0 changed their publickey which means dynamicdata cannot be used with reactive v3.0.0 even with an assembly version redirect in place.

From [Reactive v3.0.0 release notes](https://github.com/Reactive-Extensions/Rx.NET/releases/tag/v3.0.0)...
_"The strong name key has been changed. The old key was a Microsoft key that could not be fully checked-in. The new key is checked in, allowing anyone to create custom builds easily. The package names have all changed"_

Will need to update the reactive dependant reference to v3 before dynamicdata can be used with it.

**Comment by RolandPheasant** [comment]
Or perhaps I am overly complicating this and version v5 phase 1 should initially be upgrade to v3.0.0 then phase 2 should be to upgrade to dotNet Standard

**Comment by robsonj** [comment]
I'm be happy with the second approach as we aren't using dotNet Standard :-)

**Comment by RolandPheasant** [comment]
When I get back from holidays I will start a new branch and go for approach 2. I will still have to maintain 2 branches.  I will give you a shout when it is done so you can test it.

**Comment by RolandPheasant** [comment]
@robsonj I have accepted the PR and got the build working.

To used Reactive v3.0.0 you must install [DynamicData v5.0.0.2007-beta](https://www.nuget.org/packages/DynamicData/5.0.0.2007-beta)

**Comment by robsonj** [comment]
Sorry Roland, was away on vacation.

Thanks for the merge. Unfortunately I cant integrate beta's, will move to v5 as soon as a stable version is available though

**Comment by robsonj** [comment]
Hi Roland. I was wondering how close you are to creating a release version of Dynamic Data v5 please?

**Comment by RolandPheasant** [comment]
I have been holding back as I have been thinking about making some breaking changes.  However I have decided not to so I will deploy the release version in the next few days.

**Comment by robsonj** [comment]
Any further update on the new release please Roland?

**Comment by RolandPheasant** [comment]
Hi, I just deployed to v5 stable,  See [DynamicData v 5.0.4](https://www.nuget.org/packages/DynamicData/5.0.4.207)
