### ISSUE TITLE
help running out of memory, need a better suggestion/sample on observing

### ISSUE THREAD

**Issue by papyr** [RolandPheasant/DynamicData#54]
Hi, can you please help, I am using the library to watch a list of books from a table. 

```
//Books is the catalog list, title, username, checkin Date, Check Out date
var llibraryCatalog = new SourceList<Books>();
```

On the server-side I am using the reactive extensions to observe the `llibraryCatalog`. So, when the books are checked out, or check in, over due, I need to send notifications to the user. So, I created the observable and when that list changes, I write to the list.

Each user has an inbox when they login, and I need to subscribe to changes on that _filtered_ list.
`
// Users Inbox - notifications
IObservable<IChangeSet<Books>> myIntsObservable = llibraryCatalog.Connect();`

The list is at 12000 and I've 2 issues, and seeking help
1. I get an out of memory exception, or it get slow can you please help redo this better. :1234: 
2. How to implement the filter for the users, _or **Design** should I simply have one master filtered list of all late books, all new books etc, and then have the users object subscribe to it?_

thanks

**Comment by RolandPheasant** [comment]
When dynamic data is used on a server behind a service, and filtering is required there is often the need to provide custom filter handling. Do you have any simplified code for me to look at?

**Comment by papyr** [comment]
Let me get something shortly out

**Comment by papyr** [comment]
2 scenarios,

- 1. I am trying to get service tickets (on the books/publications) per user as they login and show them the list in their listview/inbox view (ASP MVC 4.5.2), I can handle the UI/View part.
- 2. What is the right design to dispatch the information per user, I can't imagine making 150 user instances, should I run one as a service and let the user objects subscribe as they log in.

```
IObservable<ServiceTickets> myObservableServiceTickets;
var myObservableServiceTicketsPerUser = myObservableServiceTickets.ToObservableChangeSet(user => user.id);
```

1. I have 150 users, and I do not want to poll the collection, the table has 1500 to 2000 moving tickets on an average. I am lost a little here, 
2. how can I subscribe per user - when he logs in, without polling. 
3. Is there a way to get a readonly collection from the DB table directly, so we can observer the tables as a collection (really sweet :cake: )

Can you help me correct the code below and map it (to table _or_ EntityFramework collection)

```
var myTicketsWatchList = myObservableServiceTicketsPerUser.Connect() 
                    .Filter(user =>user.Id == TicketStatus.Open)            
                    .Sort(myObservableServiceTicketsPerUser.Descending(t => t.Date))
                    .ObserveOnDispatcher()
                    .Bind(out list) 
                    .DisposeMany()
                    .Subscribe()
```

**Comment by RolandPheasant** [comment]
Close due to age
