### ISSUE TITLE
Observing the DB table directly

### ISSUE THREAD

**Issue by papyr** [RolandPheasant/DynamicData#55]
Hi, I know EF already has entity tracking, but its freakishly outdated and slow, which only slows down the RX lib.

For ReadOnly-Observable is there a way to hook up the table as a virtual list to the Database table and watch/subscribe to those changes.

Here is a gem https://tabledependency.codeplex.com/

**Comment by RolandPheasant** [comment]
@papyr this is the first time I have seen that library and it looks good and a match for using dd. Are you consuming it client or server side. Also do you have any sample code?

**Comment by papyr** [comment]
hi @RolandPheasant checkout NReco, since its DB independent, the tables/entities could also be observed independent of the container/db company.

**Comment by papyr** [comment]
Any chance you can support this feature, I posted the link from Nreco it has some sample code
