### ISSUE TITLE
For ChangeReason.Change, must supply previous value

### ISSUE THREAD

**Issue by molnarm** [RolandPheasant/DynamicData#56]
When transforming changes into an Observable of a single value, it is possible that the transformed value is null (e.g. when a property is not set on an object), which is perfectly normal.

However, if such a transformation leads to a result value being changed from null to something else, there is an exception thrown [in the constructor of Change](https://github.com/RolandPheasant/DynamicData/blob/master/DynamicData/Cache/Change.cs#L119) with the following message: "For ChangeReason.Change, must supply previous value". (See sample code [here](https://gist.github.com/molnarm/8e7a0555d7e22e6bbbea23596c73f9d4) for reproducing.)

**Comment by RolandPheasant** [comment]
This is by design. One of the guidelines of rx states that nulls should not be used in observable. Dynamic data complies with this.
