### ISSUE TITLE
Add OnItemAdded() for IObservableCache<TObject, TKey>

### ISSUE THREAD

**Issue by angularsen** [RolandPheasant/DynamicData#57]
```
var cache = new SourceCache<Person, int>(x => x.Id);

cache.Connect()
    .OnItemAdded(a => a.MyEvent += OnMyEvent) // does not exist
    .OnItemRemoved(a => a.MyEvent -= OnMyEvent)
    .Subscribe();
```

A similar approach works with SourceList and IObservableList, but not the cache equivalent.
Have I missed something?

Here is my current approach that seems to work if you are interested in a PR:

```
    internal static class DynamicDataEx
    {
        public static IObservable<IChangeSet<TObject, TKey>> OnItemAdded<TObject, TKey>(
            this IObservable<IChangeSet<TObject, TKey>> source,
            Action<TObject, TKey> addAction)
        {
            if (source == null)
                throw new ArgumentNullException("source");
            if (addAction == null)
                throw new ArgumentNullException("addAction");
            return new OnBeingAdded<TObject, TKey>(source, addAction).Run();

        }
    }

    internal sealed class OnBeingAdded<TObject, TKey>
    {
        private readonly Action<TObject, TKey> _callback;
        private readonly IObservable<IChangeSet<TObject, TKey>> _source;

        public OnBeingAdded(IObservable<IChangeSet<TObject, TKey>> source, Action<TObject, TKey> callback)
        {
            if (source == null)
                throw new ArgumentNullException("source");
            if (callback == null)
                throw new ArgumentNullException("callback");
            _source = source;
            _callback = callback;
        }

        public IObservable<IChangeSet<TObject, TKey>> Run()
        {
            return _source.Do(RegisterForAddition);
        }

        private void RegisterForAddition(IChangeSet<TObject, TKey> changes)
        {
            foreach (Change<TObject, TKey> change in changes)
            {
                switch (change.Reason)
                {
                    case ChangeReason.Add:
                        _callback(change.Current, change.Key);
                        continue;
                        //                        case ChangeReason.AddRange:
                        //                            change.Range.ForEach<TObject, TKey>(this._callback);
                        //                            continue;
                    case ChangeReason.Update:
                        _callback(change.Current, change.Key);
                        continue;
                    default:
                        continue;
                }
            }
        }
    }
```

**Comment by RolandPheasant** [comment]
As much as I would welcome a PR to fill the missing functionality, there is already an out of the box solution

```
var mySubscriptions = _source.Connect()
	.SubscribeMany(a =>
	{
	    a.MyEvent += OnMyEvent;
	    return Disposable.Create(() => a.MyEvent -= OnMyEvent);
	});
```
The advantage with this method is it will also dispose each item when removed or updated, and dispose all subscriptions when mySubscriptions is disposed.

If however you still with to do a PR, let me know as there are some details to account for which I should explain first

**Comment by anjdreas** [comment]
Thanks, that definitely solves my need. I still think it would be an improvement to have an extension method similar to what exists for SourceList, since at least I would not have thought of this solution on my own. I can do the PR, but you mentioned some details?

**Comment by anjdreas** [comment]
You are also right about the update case, I do want to handle event subscriptions for that case too.

**Comment by RolandPheasant** [comment]
Great, I thought there was a couple of details to consider but looking at your proposed solution, it will be easy as the concept will work. The one difference is the cache changed reason is different from the list changed reason in that it has less change reasons available.

The only other consideration is that I have recently upgraded master branch to use NetStandard. The code is identical but you will require the latest visual studio updates as well as  the latest nuget.  Fyi if you are not up speed with NetStandard there is a good explanation [here](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) and the pre-requestites page is [here](https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites)

**Comment by RolandPheasant** [comment]
This can be achieved by directly manipulating a change set so closing. If there is still demand for such an operator please reopen
