### ISSUE TITLE
Can I wrap DB table as an observable

### ISSUE THREAD

**Issue by papyr** [RolandPheasant/DynamicData#58]
Hi, is it possible to get a reader observable wrapper on a Database table, for e.g. I have a table of tickets, how do I watch the table with this lib - this would be a tremendous help.

**Comment by RolandPheasant** [comment]
That is something you would have to do manually. 

A)  load observable cache from database
B)  Monitor dB changes and load amended records. 

A DBDependency can be used to watch for the changes. Otherwise if polling you would need a store a local last read date time and continually requery based on a modified since the last read.

**Comment by papyr** [comment]
This lib, could go a long way if we connected it to the and enable `SqlDependency` we can get the cache updated without polling, I am [adding a link](http://bit.ly/2dXvuW0)




1. We need to enable the Service Broker on our database(TechBrijDB). To check, run following SQL syntax:

`SELECT name, is_broker_enabled FROM sys.databases
`
To enable service broker on TechBrijDB database:

```
ALTER DATABASE TechBrijDB SET ENABLE_BROKER
GO
```

2. To subscribe query notification, we need to give permission to IIS service account

`GRANT SUBSCRIBE QUERY NOTIFICATIONS TO “Domain\ASPNET”`


**database structure

Setup SqlDependency:**

I am using ASP.NET Web API project but same steps can be applied on other ASP.NET projects also.

3. First define connection string in web.config:


```
<connectionStrings>
    <add name="DefaultConnection" providerName="System.Data.SqlClient" connectionString="Data Source=.\SQLExpress;Initial Catalog=TechBrijDB;Integrated Security=SSPI;" />
</connectionStrings>

```

4. In Global.asax, To enable listener:
protected void Application_Start()
```
{
        //...
        SqlDependency.Start(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString); 
}
```
To stop the listener:

```
protected void Application_End()
      {          SqlDependency.Stop(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString); 
      }
```

5. Add following JobInfo and JobInfoRepository classes:


```
public class JobInfo {
  public int JobID { get; set; }
  public  string Name { get; set; }
  public  DateTime LastExecutionDate { get; set; }
  public  string Status { get; set; }
}
 
 public class JobInfoRepository {
 
    public IEnumerable<JobInfo> GetData()
    {
       
        using (var connection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
        {
            connection.Open();
            using (SqlCommand command = new SqlCommand(@"SELECT [JobID],[Name],[LastExecutionDate],[Status]
               FROM [dbo].[JobInfo]", connection))
            {
                // Make sure the command object does not already have
                // a notification object associated with it.
                command.Notification = null;
 
                SqlDependency dependency = new SqlDependency(command);
                dependency.OnChange += new OnChangeEventHandler(dependency_OnChange);
 
                if (connection.State == ConnectionState.Closed)
                    connection.Open();
 
                using (var reader = command.ExecuteReader())
                    return reader.Cast<IDataRecord>()
                        .Select(x => new JobInfo(){ 
                            JobID = x.GetInt32(0), 
                            Name = x.GetString(1), 
                            LastExecutionDate = x.GetDateTime(2),  
                            Status  = x.GetString(3) }).ToList();       
         }
        }        
    }
    private void dependency_OnChange(object sender, SqlNotificationEventArgs e)
    {            
        JobHub.Show(); 
    }
 
 
}
```

**Comment by RolandPheasant** [comment]
That's just about it.  All you need to do is maintain a cache with the latest data.

**Comment by papyr** [comment]
My original question was around wrapping table entities to get this functionality. I posted the code to see if we can 
Hoping you can bake it generically so it can be applied to other entities. With the way it is, its my end with repetition, I also think others who use your lib will benefit if we make this part of the lib.

**Comment by RolandPheasant** [comment]
I will take a look. Should be easy.

**Comment by RolandPheasant** [comment]
The task can be split into a few steps.  NB: This code is untested

Step 1. Make the data observable. See [Observable SQL data](https://gist.github.com/RolandPheasant/a56bf397d22e05c8995407be941c56f9)
Step 2. Populate a dynamic data cache see [Populate repository](https://gist.github.com/RolandPheasant/91cb2d3cb685eab49a937c1afbd7d60e)
Step 3: Abstract repository using generics [Not yet done]
Step 4. Pipeline data to SignalR hub [Not yet done]

**Comment by papyr** [comment]
Hi @RolandPheasant this would be helpful, any chance it could be included in the next release.
