### ISSUE TITLE
Can't use DynamicData 5.0.5.2078 in Profile111 

### ISSUE THREAD

**Issue by ilexius** [RolandPheasant/DynamicData#60]
Hi,
I have a problem using the current stable in Profile111 (Xamarin Partable Library):

`C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "DynamicData, Version=5.0.5.2078, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111".`

I installed the nuget package without problems, no dependency errors.
Am I doing anything wrong here? Thank you, this is an amazing library!!!

**Comment by RolandPheasant** [comment]
Thanks for the positive statement. Much appreciated,

If you try adding the Rx 3.0 libraries without using Dynamic Data, do you still get the same problem?

The problem may be related to this https://github.com/Reactive-Extensions/Rx.NET/issues/261

Alternatively, you could try and use Dynamic Data 4.9 which is based on Rx 2.2 and has 99% the same API as Dynamic Data 5.x

**Comment by cubed-it** [comment]
If I may jump in here. I know this issue from one of my PCLs already. This was fixed in VS hotfix 14.0.25431.01. https://github.com/dotnet/roslyn/issues/11067

**Comment by RolandPheasant** [comment]
@cubed-it thanks for the info.
