### ISSUE TITLE
GroupOn does not bind to target collection when only items within a group have changed.

### ISSUE THREAD

**Issue by sfmskywalker** [RolandPheasant/DynamicData#69]
When I have a source collection that I project into a target collection with grouping, the target collection is correctly updated **if a new item is added that causes the creation of a new group**.
If I add an item to the source list that does not cause the creation of a new group, then the target collection won't reflect the newly added item.

The following unit test shows this issue clearly:

```C#
// A sample source list.
var sourceList = new ObservableCollection<string>(new[]
{
    "Ape",
    "Ant",
    "Bear",
    "Boar",
    "Cougar",
});

// The target list to update when the source list changes.
var targetList = new ObservableCollectionExtended<IGroup<string, char>>();
bool targetListIsUpdated;

sourceList
    .ToObservableChangeSet()
    .Sort(SortExpressionComparer<string>.Descending(x => x))
    .GroupOn(x => x[0])
    .Bind(targetList)
    .Subscribe(x =>
    {
        targetListIsUpdated = true;
    });

// This will pass the assert, because a new group will be created (there's no group by 'D' yet).
targetListIsUpdated = false;
sourceList.Add("Dolphin");
Assert.IsTrue(targetListIsUpdated);

// This will fail the assert, because no new group is created (there's already a group by 'A').
targetListIsUpdated = false;
sourceList.Add("Algae");
Assert.IsTrue(targetListIsUpdated);
```

**Comment by sfmskywalker** [comment]
I did notice that the `GroupOn` method supports an optional parameter called `regrouper`, but I haven't figured out its purpose yet.

**Comment by RolandPheasant** [comment]
For the GroupOn operator, this is the expected behavior. New groups are added when items match the group value, and groups are removed when  there are no longer an items in the group. 

The value of the inner group is represented by an observable list for each matched group. When values matching the inner grouping are modified, it is the inner group which produces the changes.

This is the default behavior for grouping on a cache or a list. 

However this is not always the desired behavior so recently there has been a new operator introduced ``GroupWithImmutableState``` which will produce a grouping who's inner items are a fixed size array.  This should produce the behavior which you expect.

**Comment by RolandPheasant** [comment]
Btw I have sent an invitation to the slack forum. Feel free to sign in and ask any questions there.

**Comment by RolandPheasant** [comment]
Also the regrouper overload is used to force reevaluation of a grouping when the group function is mutable or an impure function. 

For example if you have a time based grouping with values like `Last Minute', 'Last Hour', 'Today' etc regrouper is used to refresh these groupings

**Comment by sfmskywalker** [comment]
Roland, this is brilliant. Thank you so much for the detailed explanation, the `GroupWithImmutableState` is precisely what I need in my case.

Regarding the regrouper overload, I might ask the question on Slack as to how construct one.

Thanks again mate, this really helped.
