### ISSUE TITLE
TransformMany of ReactiveList use add / remove rather than replace

### ISSUE THREAD

**Issue by modplug** [RolandPheasant/DynamicData#70]

**Comment by RolandPheasant** [comment]
Although the PR appears to fix the issue, there was already an underlying issue with the way the operator handles Replaced items. It erroneously assumed that the original parent would contain the same items as the previous parent.

**Comment by RolandPheasant** [comment]
The original issue is now fixed. However I am unsure whether it will be possible deterministically apply a replace being as a parent replace does not necessarily mean that a child has been replace. @modplug I will leave this one for you to check out

**Comment by RolandPheasant** [comment]
This is an old one, transform many works. However dues to the nature of combining lists, replace is not possible
