### ISSUE TITLE
Feature request: ability to dynamically control resetThreshold 

### ISSUE THREAD

**Issue by KennethKr** [RolandPheasant/DynamicData#74]
I have a case where I do manual sorting in my UI using drag and drop. 

The code below shows how I currently set up my DD binding.

`			model.ShipmentCache
.Connect()
.Transform(t => CreateShipmentViewModel(t))
.BatchIf(batchUpdate, true, null, null)
.Sort(sortObservable, resetThreshold: 30)
.ObserveOn(SynchronizationContext.Current)
.Bind(out viewModels).Subscribe();`

When I manually move the items in UI, the updates from DD will be off when sorting in the future, as DD indexes is no longer in sync with the UI. This is only a problem when the resetThreshold is set > 1. When resetThreshold is used, DD won't issue updates, and the problem is solved for my part. 

One possible solution would be a dynamic way of controlling resetThreshold, either by an observable or some other means. This would mean that I could set my resetThreshold to 1 when performing manual sorting, and set it back to a higher number enabling updates when I'm done sorting manually.

**Comment by RolandPheasant** [comment]
This is a good suggestion and certainly a candidate for an extension.

Before proceeding, did you know that there are 2 reset thresholds. One for the Sort() operator and one for Bind(). 

It may be possible to make use of the overload of bind() which accepts ISortedObservableCollectionAdaptor which allows custom control of binding.

**Comment by RolandPheasant** [comment]
@KennethKr I have added an example for how you may achieve the desired result. See [CustomBinding.cs](https://github.com/RolandPheasant/DynamicData.Snippets/blob/master/DynamicData.Snippets/Sorting/CustomBinding.cs).

You will need to increase (or removed) the threshold which you use on the following
```
.Sort(sortObservable, resetThreshold: 30) 
```

Let me know if it works and maybe I can then look into adding tan overload to DD to achieve the same thing out of the box

**Comment by KennethKr** [comment]
A bit late. Thank you, I will follow up on this shortly.

**Comment by KennethKr** [comment]
@RolandPheasant It seems to do what it is intended to do. Except: you did not add a check for resetThreshold on reorder? That's really what my need is, so I added it myself. Then the whole thing seems to work like a charm.

**Comment by RolandPheasant** [comment]
The reason for that is reorder always sends a reset. However that could easily be changed

**Comment by KennethKr** [comment]
Are you sure reorder always sends reset? 

I could have dreamt it, but I thought @modplug changed that at some point.

**Comment by KennethKr** [comment]
Seems that after I set the resetThreshold to 0, make some changes, set it back to a high value, some internal state is destroyed. First I get a lot of updates, then when I make changes again it doesnt issue any updates.

**Comment by RolandPheasant** [comment]
[PR for sort threshoold](https://github.com/RolandPheasant/DynamicData/pull/68/files).

You are correct, the re-order should also be modified to respect the sort threshold

**Comment by RolandPheasant** [comment]
Closed - the is a working example in snippets
