### ISSUE TITLE
Filter and sort broken in 4.11.3.1209

### ISSUE THREAD

**Issue by njannink** [RolandPheasant/DynamicData#77]
Filter and Sort is broken in 4.11.3.1209 version. I rolled back to the 4.11.2 version and there it works fine

**Comment by RolandPheasant** [comment]
Could you be a little more specific please.

**Comment by njannink** [comment]
The following setup code in my collection that works perfectly with 4.11.2 and when I updated to 4.11.3 it stopped working. The connection doesn't seem to watch / observe the filter and sorter anymore.

```
public ObservableCollection(IConnectableCache<T, string> source, Func<T, TResult> transform, IScheduler scheduler, IApplicationConfiguration config)
{
    _pageData = new PageParameterData(1, config.PageSize);

    var pager = Pager.WhenValueChanged(x => x.CurrentPage)
        .Select(page => new PageRequest(page, config.PageSize))
        .StartWith(new PageRequest(1, config.PageSize))
        .DistinctUntilChanged();

    var filter = this.WhenPropertyChanged(x => x.Filter)
        .Throttle(TimeSpan.FromMilliseconds(250))
        .Select(x => x.Value ?? NoFilter);

    var sorter = this.WhenValueChanged(x => x.Sort)
        .Where(x => x?.Item1 != null)
        .Select(x => x.Item2
            ? SortExpressionComparer<TResult>.Ascending(x.Item1)
            : SortExpressionComparer<TResult>.Descending(x.Item1));

    var connection = source.Connect()
        .Transform(transform)
        .Filter(filter)
        .Sort(sorter)
        .Page(pager)
        .Do(x => _pageData.Update(x.Response))
        .ObserveOnSafe(scheduler)
        .Bind(_collection)
        .DisposeMany()
        .Subscribe();

    var changes = Observable
        .FromEventPattern<NotifyCollectionChangedEventHandler, NotifyCollectionChangedEventArgs>(
            x => _collection.CollectionChanged += x,
            x => _collection.CollectionChanged -= x)
        .ObserveOnSafe(scheduler)
        .Select(x => x.EventArgs)
        .Subscribe(x => CollectionChanged?.Invoke(this, x));

    _cleanup = new CompositeDisposable(connection, changes);
}
```

**Comment by RolandPheasant** [comment]
I cannot see anything obvious. Have you checked for exceptions using the error channel?

**Comment by RolandPheasant** [comment]
I have a near identical example to your code on dynamic trader. I will try it with 4.11.3 tonight.

**Comment by njannink** [comment]
That example was the main source for my code.

Sorry I also didn't have time anymore yesterday evening to look further into it. Maybe tonight or tomorrow I find the time. For now the 4.11.2 is a good workaround.

**Comment by RolandPheasant** [comment]
I upgraded dynamic trader to v4.11.3.1209 and the paged example still works

**Comment by njannink** [comment]
Im a bit busy atm. I will attach the 4.11.3 to my own code this sunday or after the weekend and let you know what I find. Which branch\tag is the 4.11.3 release?

**Comment by RolandPheasant** [comment]
Grab the code in this branch [Version 4](https://github.com/RolandPheasant/DynamicData/tree/Version4). Although I did not create a tag, the code is unchanged since.

Btw for future releases I will make sure I create tags.

**Comment by njannink** [comment]
I did some quick debugging and I get an SortException in the FilteredIndexCalculator on line 90. The merged changeset from master is that big that I cannot quickly see which change caused this to happen.

**Comment by RolandPheasant** [comment]
That's odd that you are getting this exception now, as that code has not substantially changed for years so I am baffled why you are getting it now. The only difference is the following line (I checked the object history):
```
if (insertIndex < 0)
             throw new SortException("Cannot determine current index");
```
Beforehand it threw an index out of range exception when that condition was hit which was not a very helpful exception which is why I added the code.  I have seen this error condition hit on objects which are mutable and have a variable hash code (i.e. the default one which is based on all values). If the object is mutable, try and implement a hash code based solely on the key value which is important for ```IndexOf()`` operations. 

Failing that, I am left scratching my head.

**Comment by RolandPheasant** [comment]
I just realised why the condition has been hit.  The change is ```ChangeReason.Move``` which can only possibly be hit after the sort comparer has changed.  Check out [this commit](https://github.com/RolandPheasant/DynamicData/commit/9e97d728d849efea3c3ee0eb2fc8e5dd9d6adaaf) to see what is different with sorting.

The change was necessary so a consumer can apply animations on the UI when the comparer changed - previously the comparer change would always reset the entire list even for a small number of changes.  

But even then the condition can only be hit when ```Sort(myComparer, resetThresohold: 100)``` overload is used. Have you set the threshold? If so, try removing the threshold to see if the problem goes away. 

So where does this leave us? Possibly one of the following

1. Mutable object which has changed - if so implement a non-changing has code (as per previous comment)
2. Using reset threshold - try removing it to see what happens
3. Failing the above, the only way I am going to to get to the root of the matter is to be able to replicate the issue in test code

**Comment by RolandPheasant** [comment]
I've found the problem and I am working on a fix

**Comment by RolandPheasant** [comment]
@njannink this should be fixed now. Update to the latest Nuget version and let me know how you get on

**Comment by njannink** [comment]
Thanks I will test it tonight and let you know

**Comment by njannink** [comment]
Tested 4.12.0 and it works. Thanks again for the quick fix
