### ISSUE TITLE
Add SourceCache.Create method similar to Observable.Create

### ISSUE THREAD

**Issue by gsivorot** [RolandPheasant/DynamicData#88]
Encapsulate the creation of SourceCache by following a pattern similar to Observable.Create.  You could have a SourceCache.Create method that passes in a Func<SourceCache> and you can return a single IDisposable or an IEnumerable<IDisposable> from within that method. The SourceCache.Create method itself would return an IObservableCache<> instead of a SourceCache<>.

**Comment by RolandPheasant** [comment]
I love this idea and have immediate begun to consider what the api should look like.

For the observable list it will be easy to make an api almost identical to Observable.Create<T>.  Here are some examples

```
IObservable<IChangeSet<int>> ocs1 = ObservableChangeSet.Create<int>(list =>
    {
        list.AddRange(Enumerable.Range(1,100));
        return () => { };
    });

IObservable<IChangeSet<int>> ocs2 = ObservableChangeSet.Create<int>(list =>
    {
        list.AddRange(Enumerable.Range(1, 100));
        return new CompositeDisposable();
    });

IObservable<IChangeSet<int>> ocs3 = ObservableChangeSet.Create<int>(async list =>
    {
        var value = await Create<int>();
        list.Add(value);

        return () => { };
    });

//would include all Observable.Create overloads which rx has
```

What is immediately clear is I would also have to make the data source subject like i.e. it would have to be able handle OnError and OnComplete. So rather than dealing with an observable list or cache I would introduce a new data source subject.

And similarly for a cache 
```
IObservable<IChangeSet<Person, string>> ocs1 = ObservableChangeSet.Create<Person,string>(dataSource =>
    {

        return () => { };
    });
    
IObservable<IChangeSet<Person, string>> ocs2 = ObservableChangeSet.Create<Person, string>(async dataSource =>
    {
        var value = await Create<Person>();
        dataSource.AddOrUpdate(value);

        return () => { };
    });
```

The only thing which I am unsure about is how can I get the key  selector into the about function.  Any ideas?

**Comment by RolandPheasant** [comment]
Actually it's easy

```
IObservable<IChangeSet<Person, string>> ocs3 = ObservableChangeSet.Create<Person, string>(dataSource =>
{
	return new CompositeDisposable();
}, p => p.Name);
```

**Comment by RolandPheasant** [comment]
I have introduced a new static class ObservableChangeSet which can be used for create observable caches and observable lists.  I have implemented the same overloads which exist for Observable.Create<T>.

# To create from observables

```
IObservable<IEnumerable<Person>> LoadPeople() =>Observable.Return(Enumerable.Empty<Person>());
IObservable<IEnumerable<Person>> SubscribePeople() => Observable.Return(Enumerable.Empty<Person>());

IObservable<IChangeSet<Person>> listFromObservable = ObservableChangeSet.Create<Person>(list =>
        {
            var peopleLoader = LoadPeople().Subscribe(list.AddRange, list.OnError);
            var peopleSubscriber = SubscribePeople().Subscribe(list.AddRange, list.OnError);
            return new CompositeDisposable(peopleLoader, peopleSubscriber);
        });

IObservable<IChangeSet<Person, string>> cacheFromObservable = ObservableChangeSet.Create<Person, string>(cache =>
        {
            var peopleLoader = LoadPeople().Subscribe(cache.AddOrUpdate, cache.OnError);
            var peopleSubscriber = SubscribePeople().Subscribe(cache.AddOrUpdate, cache.OnError);

            return new CompositeDisposable(peopleLoader, peopleSubscriber);
        }, p=>p.Name);

```
# To create from tasks

```
Task<IEnumerable<Person>> LoadPeopleAsync() => Task.FromResult(Enumerable.Empty<Person>());

IObservable<IChangeSet<Person>> listFromTask = ObservableChangeSet.Create<Person>(async list =>
        {
            var people =await LoadPeopleAsync();
            list.AddRange(people);
        });

IObservable<IChangeSet<Person, string>> cacheFromTask = ObservableChangeSet.Create<Person, string>(async cache =>
        {
            var people = await LoadPeopleAsync();
            cache.AddOrUpdate(people);
        }, p => p.Name);
```

The resulting changes sets can be converted to a cache or list by calling ```ToObservableCache()``` or ```ToObservableList()``` respectively.

The great advantage of doing it this way is the result is a first class Rx citizen in that repeat and retry ogic can be easily implemented - I will create some examples at a later date of doing so.

The API will be released soon,

The API has not yet been released but hopefully

**Comment by RolandPheasant** [comment]
Implemented and deployed
