### ISSUE TITLE
Filtering on calculated values

### ISSUE THREAD

**Issue by apobekiaris** [RolandPheasant/DynamicData#90]
Hi

Thanks for sharing this lib, I read many times your posts especially https://dynamic-data.org/2014/12/21/trading-example-part-4-filter-on-calculated-values/
However is not clear to me how deep this problem is solved or if there are other means build-in. What about if there are a number of bad trades and then the price drops back to the normal levels, will this demo code exclude all the outliers. From what I understand it does not work with median, mode values and what about buffer overlaps? Could you share some thoughts please.

**Comment by RolandPheasant** [comment]
The trading demo is stripped down and very simple illustration of how changing data can be shaped and with ease.

The basic idea behind filtering is that you supply a predicate, where the predicate can be anything want. So if you want to add additional criteria you can easily change the predicate. 

The second part to filtering is the ability to dynamically re-apply a filter be it as a result of a property changed or a value from some observable. Dynamic Data supplies a rich API which gives you several options for re-apply a filter.

There are some better examples complete with unit tests in [the snippets project](https://github.com/RolandPheasant/DynamicData.Snippets).  For examples of filtering see [Filter Examples](https://github.com/RolandPheasant/DynamicData.Snippets/tree/master/DynamicData.Snippets/Filter) and [Mutable ValuesExamples](https://github.com/RolandPheasant/DynamicData.Snippets/tree/master/DynamicData.Snippets/MutableValues)

Btw FilterController is obsolete now and is replaced directly with IObservable<Func<T,bool>> which is an observable filter.

Also the forum is now on Slack. If you wish to ask further questions, send me your email address to roland_pheasant@hotmail and I will send an invite

**Comment by RolandPheasant** [comment]
Closed due to no additional discussion
