### ISSUE TITLE
Create a list of data from SourceCache

### ISSUE THREAD

**Issue by crosscourt** [RolandPheasant/DynamicData#92]
What is the easiest way to get a List<T> of data from a SourceCache<T, Key>?

I tried this:
var cleanup = myCache.Connect().Take(1).Flatten().Select(i => i.Current).Subscribe(a =>
            {
                list.Add(a);
            });
cleanup.Dispose();

I also tried ForEachAsync but that waits for items to arrive even if the cache is empty.

myCache.Connect().Take(1).Flatten().Select(i => i.Current).ForEachAsync(a =>
            {
                list.Add(a);
            });

**Comment by RolandPheasant** [comment]
To reactively get the data use the ToCollection() operator. 

To imperatively get the data use Items property of the cache

**Comment by RolandPheasant** [comment]
As a general rule, dd does not produce empty results i.e. ToCollection will not produce until initial data is present. If results are always required use ToCollection ().StartWithEmpty().

**Comment by crosscourt** [comment]
so like this?

            var tags = new List<Tag>();
            _repository.Tags.Connect(tag => tag.ConfigId == configId).Transform(ConvertItem).ToCollection().StartWithEmpty().Subscribe(c => tags = c.ToList());

            var tags2 = _repository.Tags.Items.Where(tag => tag.ConfigId == configId).Convert(ConvertItem).ToList();

**Comment by RolandPheasant** [comment]
Both options are viable. However it is always better to use the ToCollection overload as it is reactive and will produce a new and thread safe list after each change to the content of the source cache.

The best solution will be determined by what you need the list for ie what are you doing with the data. What I would normally do is to expose the resulting list as an observable. So instead to ToCollection(). Subscribe(...), I would use .Select() and return IObservable<List<T>>.

In your use case, what are you doing with the resulting list?

**Comment by crosscourt** [comment]
Its an API call for the client to get a snapshot of the data from the server.

For some things, i have made the reactive subscription work over wcf between client and server.
For other things, i just want to get a list of data back to the client even if its reactive on the server side.

**Comment by RolandPheasant** [comment]
For snapshot your options are open. I would probably expose IObservable<List> and in the service implemention do an obs.Take(1).Wait() and return that. Probably also worth adding a Replay(1).RefCount() to the observable<list> if you are expecting simultaneous client calls.

Out of curiosity, for the subscription what is returned to the client?

**Comment by crosscourt** [comment]
IChangeSet is converted to a SerializedChangeSet passed to a callback method.

I'm not familar with Wait and Replay/RefCount.
Will Wait() wait forever if there is nothing in the cache? thanks

**Comment by RolandPheasant** [comment]
Replay / refcount ensures that when you have more than subscriber at the same time the content of the observable is produced only once.

Wait would normally wait until there is something in the cache. This is guarded against by use of the start with operator (mentioned above).

What you are doing sounds like a good example for others. Perhaps you can help me reproduce the example in [dynamic data snippets](https://github.com/RolandPheasant/DynamicData.Snippets)
