### ISSUE TITLE
SourceCache.Refresh() hangs

### ISSUE THREAD

**Issue by moonolgerd** [RolandPheasant/DynamicData#93]
I defined SourceCache instance
`private readonly SourceCache<IOrderBlotterItemViewModel, int?> _sourceCache = new SourceCache<IOrderBlotterItemViewModel, int?>(p => p.OrderId);`

Constructor builds the subscription:

            orderBlotterViewModel.Items.ObserveCollectionChanged()
                .Subscribe(p => _sourceCache.AddOrUpdate(p.EventArgs.NewItems.Cast<IOrderBlotterItemViewModel>()));
            _disposable = _sourceCache.AsObservableCache()
                .Connect(p => p.Status == Status || Status == null)
                .Filter(predicate)
                .FilterOnProperty(p => p.OrderStatusText, p => Status == null || p.Status == Status)
                .Bind(out _data)
                .Batch(TimeSpan.FromSeconds(0.5))
                .DisposeMany()
                .Subscribe(p =>
                {
                    if (p.Count > 0)
                        OnPropertyChanged(nameof(Header));
                });
        }`

Then I call `_sourceCache.Refresh();`

The code hangs in ObservableCache on _if (_countChanged.IsValueCreated)_

`        private void InvokeNext(IChangeSet<TObject, TKey> changes)
        {
            if (changes.Count == 0) return;

            lock (_locker)
            {
                try
                {
                    _changes.OnNext(changes);

                    if (_countChanged.IsValueCreated)
                        _countChanged.Value.OnNext(_readerWriter.Count);
                }
                catch (Exception ex)
                {
                    _changes.OnError(ex);
                }
            }
        }`

**Comment by RolandPheasant** [comment]
Does this happen repeatedly?

**Comment by moonolgerd** [comment]
Yes, every time. Thanks for looking into it

**Comment by RolandPheasant** [comment]
Would it be possible to create a simple version of your code which I can somehow debug? 

Otherwise if you can explain what you are trying to achieve  I may be able to give a work around.

It has been years since a deadlock has been reported so I am surprised

**Comment by RolandPheasant** [comment]
Also, what is the reason for calling Refresh. I ask because all adds, updates and removes will automatically refresh, and refresh is a means to handle inline object changes

**Comment by moonolgerd** [comment]
Hi Ronald, never mind. Looks like I don't need refresh like you mentioned. Closing it as non-issue. Thanks!
