### ISSUE TITLE
ExpireAfter does not trigger when using default scheduler

### ISSUE THREAD

**Issue by crosscourt** [RolandPheasant/DynamicData#94]
It seems to only work when I use TaskPoolScheduler.Default
Do timers not work in single threads with Scheduler.Default?

**Comment by RolandPheasant** [comment]
Timers have to run on a background thread to work.

**Comment by RolandPheasant** [comment]
Btw are you on Slack? These kind of questions are easier to ask on the forum. If you want an invite send an email to roland.pheasant@gmail.com and I will send an invite

**Comment by RolandPheasant** [comment]
Close dues to being a general rx concern not specifically dd
